### ISSUE TITLE
Azure Machine Learning Workbench

### ISSUE THREAD

**Issue by hau-mal** [mspnp/architecture-center#1005]
The Azure Machine Learning Workbench has been deprecated. Deployment to Azure ML Service is API based. Please change accordingly, see also https://docs.microsoft.com/en-us/azure/machine-learning/service/overview-what-happened-to-workbench 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0bdc71b-0a54-4cc4-1b79-f60e274e9a51
* Version Independent ID: 1783570c-3545-71c8-72d3-d5657f77c070
* Content: [Choosing a machine learning technology](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/data-science-and-machine-learning)
* Content Source: [docs/data-guide/technology-choices/data-science-and-machine-learning.md](https://github.com/mspnp/architecture-center/blob/master/docs/data-guide/technology-choices/data-science-and-machine-learning.md)
* Service: **guidance**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @hau-mal Thank you for reporting this issue! We will investigate and make any necessary changes.

**Comment by amitpatelupw** [comment]
Sure
