### ISSUE TITLE
Update Batch AI references

### ISSUE THREAD

**Issue by rahulai** [mspnp/architecture-center#1093]
Update/replace 'Azure Batch AI' with 'Azure Machine Learning Compute'.
https://docs.microsoft.com/en-us/azure/batch-ai/overview-what-happened-batch-ai 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8076098f-ba53-c7f9-b12f-4b83fd4ad4e5
* Version Independent ID: 9878fb7d-b529-326b-1dc8-9126c79ce60c
* Content: [Batch scoring of Python models on Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/ai/batch-scoring-python)
* Content Source: [docs/reference-architectures/ai/batch-scoring-python.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/ai/batch-scoring-python.md)
* Service: **guidance**
* GitHub Login: @njray
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Thanks - the Azure CAT team is currently working on an update to this architecture. Stay tuned 😺

**Comment by MikeWasson** [comment]
@rahulai FYI, we just published an update of this article to use Machine Learning Service
