### ISSUE TITLE
Detailed Azure hybrid cloud example explaination

### ISSUE THREAD

**Issue by cheungderek** [mspnp/architecture-center#1095]
Readers who are new to Azure networking may find my below article using in understanding this Azure hybrid cloud reference architecture example:

http://clcnetwork.wordpress.com/2018/12/12/extending-private-data-center-to-azure-cloud-part-2/

Regards
Derek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74bb4b25-ebe2-264d-047d-3f651c52a9c5
* Version Independent ID: aed6ebef-6157-9608-3f85-0807c7fdf61d
* Content: [Implement a secure hybrid network architecture - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/secure-vnet-hybrid)
* Content Source: [docs/reference-architectures/dmz/secure-vnet-hybrid.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/dmz/secure-vnet-hybrid.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @cheungderek Thank you for sharing! Surely, this will benefit others visiting this thread :)

We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
