### ISSUE TITLE
Publish/Subscribe Eqnuiry

### ISSUE THREAD

**Issue by CWJie91** [mspnp/architecture-center#1112]
Hello, it is possible 1 consumer listen to more than one queue? If both queue is filled with message and is there any setting to set which queue high priority so that the program always will consume the message from high priority queue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9425297d-8ddb-c092-5c2a-79015f4e8954
* Version Independent ID: 95fcd443-8a9f-0838-e73a-c6578f2d57f8
* Content: [Competing Consumers](https://docs.microsoft.com/en-us/azure/architecture/patterns/competing-consumers)
* Content Source: [docs/patterns/competing-consumers.md](https://github.com/mspnp/architecture-center/blob/master/docs/patterns/competing-consumers.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
In terms of the design pattern, yes a consumer can listen to multiple queues. Having a "priority" queue and "normal" queue is a common approach. The implementation will depend on what queue mechanism you use.
