### ISSUE TITLE
Please remove advice to have leading zeros in instance names

### ISSUE THREAD

**Issue by artisticcheese** [mspnp/architecture-center#1119]
Re: https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions?WT.mc_id=ITOpsTalk-blog-socuff#use-affixes-to-avoid-ambiguity
Please either explain why leading zeros are recommended per article or advice against using leading zeros. They cause nothing but trouble for automation and accomplishes nothing as far as I can see.

**Comment by MikeWasson** [comment]
There may be some value for humans in terms of alphabetical sorting, but I see that our own IaaS reference architectures don't use leading zeroes.  😄 The high-level point is to pick a consistent convention.
