### ISSUE TITLE
Can we monitor Both Platform together 

### ISSUE THREAD

**Issue by biren1234** [mspnp/architecture-center#1120]
Can we monitor Both Platform together like there are any monitoring loot for both Platform

**Comment by mike-urnun-msft** [comment]
Hi @biren1234 Thank you for your feedback! Could you clarify which documentation you're referring to? Please provide us with the URL of the documentation so that we ensure you feedback is addressed by the right team.

**Comment by KetanChawda-MSFT** [comment]
@biren1234 can you please provide the link to the document which you are referring for this issue?

**Comment by KetanChawda-MSFT** [comment]
@biren1234 Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
