### ISSUE TITLE
incorrect Hyper Link 

### ISSUE THREAD

**Issue by suravarapuVikranth** [mspnp/architecture-center#1121]
the "conditional element" hyper link is not pointing to the correct section. To my knowledge it should be point to this link " https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-templates-resources#condition". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ada6b9c1-42f6-5012-9201-04fd463efdfd
* Version Independent ID: 16abf6b9-c81a-a6f7-d0fd-b22ef3a4a744
* Content: [Conditionally deploy a resource in an Azure Resource Manager template](https://docs.microsoft.com/en-us/azure/architecture/building-blocks/extending-templates/conditional-deploy)
* Content Source: [docs/building-blocks/extending-templates/conditional-deploy.md](https://github.com/mspnp/architecture-center/blob/master/docs/building-blocks/extending-templates/conditional-deploy.md)
* Service: **guidance**
* GitHub Login: @petertay
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Good catch, thanks 😺
