### ISSUE TITLE
Section: "Considerations for Implementing a Virtual datacenter?" Feedback: First section has the same content twice.

### ISSUE THREAD

**Issue by ryancfields** [mspnp/architecture-center#1136]
Same content twice in the first section of "Considerations for Implementing a Virtual datacenter":

Identity and directory services
Identity and directory services are a key aspect of all datacenters, both on-premises and in the cloud. Identity is related to all aspects of access and authorization to services within the VDC. To make sure that only authorized users and processes access your Azure account and resources, Azure uses several types of credentials for authentication. These include passwords to access the Azure account, cryptographic keys, digital signatures, and certificates.

Identity and Directory Service
Identity and Directory services are a key aspect of all datacenters, both on-premises and in the cloud. Identity is related to all aspects of access and authorization to services within a VDC implementation. To help ensure that only authorized users and processes access your Azure Account and resources, Azure uses several types of credentials for authentication. These include passwords (to access the Azure account), cryptographic keys, digital signatures, and certificates. Azure Multi-Factor Authentication (MFA) is an additional layer of security for accessing Azure services. Azure MFA provides strong authentication with a range of easy verification options — phone call, text message, or mobile app notification — and allow customers to choose the method they prefer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d8a578-f9f1-53af-64d0-808f1fde6c9c
* Version Independent ID: 8a647cb7-2d10-53ed-5459-4356ef607e77
* Content: [Azure virtual datacenter: A network perspective](https://docs.microsoft.com/en-us/azure/architecture/vdc/networking-virtual-datacenter)
* Content Source: [docs/vdc/networking-virtual-datacenter.md](https://github.com/mspnp/architecture-center/blob/master/docs/vdc/networking-virtual-datacenter.md)
* Service: **virtual-network**
* GitHub Login: @tracsman
* Microsoft Alias: **jonor**

**Comment by MikeWasson** [comment]
Thanks - maybe a badly resolved merge conflict 😺
