### ISSUE TITLE
Not able to deploy the template

### ISSUE THREAD

**Issue by adupap** [mspnp/architecture-center#1147]
while deploying the template from

https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/devops-with-aks#deploy-the-scenario

getting an error about orchestrator version

{
  "telemetryId": "21d1d05e-af6c-42fb-abde-58c0d41acfe2",
  "bladeInstanceId": "Blade_055ae889f2614711ad51353724c2c304_0_0",
  "galleryItemId": "Microsoft.Template",
  "createBlade": "DeployToAzure",
  "code": "InvalidTemplateDeployment",
  "message": "The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is 'de3f6c30-20f7-4183-a637-e9b73a5adf32'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.",
  "details": [
    {
      "code": "InvalidParameter",
      "message": "Provisioning of resource(s) for container service aksxagqfnai6djre in resource group adupatemplate failed. Message: {\n  \"code\": \"InvalidParameter\",\n  \"message\": \"The value of parameter orchestratorProfile.OrchestratorVersion is invalid.\",\n  \"target\": \"orchestratorProfile.OrchestratorVersion\"\n }. Details: "
    }
  ]
}

**Comment by mike-urnun-msft** [comment]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5978df0f-98f5-f365-1912-48fc8c27566e
* Version Independent ID: 4f2b4216-1cc7-a267-eee4-d7716ce5ed03
* Content: [CI/CD pipeline for container-based workloads - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/devops-with-aks#deploy-the-scenario)
* Content Source: [docs/example-scenario/apps/devops-with-aks.md](https://github.com/mspnp/architecture-center/blob/master/docs/example-scenario/apps/devops-with-aks.md)
* Service: **guidance**
* GitHub Login: @iainfoulds
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @adupap Thank you for your feedback! We will review and update as appropriate.

**Comment by padupa-eeoc** [comment]
Thank you! was able to deploy after i change the kubernetes version in the template to 1.11.4

**Comment by adupap** [comment]
Thank you! i was able to deploy after i changed kubernetes version in the template to 1.11.4

**Comment by KetanChawda-MSFT** [comment]
@adupap I am glad that you figured out the issue and confirmed that it is working now as expected. We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
