### ISSUE TITLE
The first link "Active Directory Federation Services (AD FS)" points to the wrong page

### ISSUE THREAD

**Issue by KimForss** [mspnp/architecture-center#1172]
The first link https://technet.microsoft.com/windowsserver/dd448613.aspx should be https://docs.microsoft.com/en-gb/windows-server/identity/active-directory-federation-services 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e67f48d5-1891-05be-e74f-d4003e9f8bea
* Version Independent ID: 5ac877a7-dce1-ca0a-4487-d0336a351581
* Content: [Extend on-premises AD FS to Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adfs)
* Content Source: [docs/reference-architectures/identity/adfs.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/identity/adfs.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
thanks! 😺
