### ISSUE TITLE
Unable to Find Packages

### ISSUE THREAD

**Issue by tshinkle** [mspnp/architecture-center#1174]
I'm getting a ton of errors (85 in total and 166 warnings) in this code. There are clearly some dependencies and prerequisites that are not listed above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 059ca2fe-51fb-9226-6669-c4001c8bc8b8
* Version Independent ID: 982fc74f-5fc1-55a0-ba94-711b07430364
* Content: [Run the Surveys application](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/run-the-app)
* Content Source: [docs/multitenant-identity/run-the-app.md](https://github.com/mspnp/architecture-center/blob/master/docs/multitenant-identity/run-the-app.md)
* Service: **guidance**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Are you using Visual Studio 2017? You need to have the [ASP.NET and web development workload](https://visualstudio.microsoft.com/vs/support/selecting-workloads-visual-studio-2017/) installed.

**Comment by tshinkle** [comment]
Yes, and yes it is installed. Thanks.

**Comment by MikeWasson** [comment]
Sorry, I think I mis-read your reply. With the web dev workload installed, the solution doesn't build?

**Comment by tshinkle** [comment]
I installed all the options I could find for VS 2017 and updated it and it
still does not build without errors.

However, I am now down to three errors.

The first one being:
Unable to find package xunit.runner.visualstudio. No packages exist with
this id in source(s): C:\Program Files\dotnet\sdk\NuGetFallbackFolder,
Microsoft Visual Studio Offline Package.

Thanks,
Tim

**Comment by tshinkle** [comment]
Well, I've managed to narrow it down to three errors and 15 warnings. But the main issue now is the complete inability for IIS Express to update the configuration file "applicationhost.config" it created itself (and no, it is not encrypted, nor is it read-only) . Has anybody actually run this code following the steps listed above successfully?

**Comment by woodp** [comment]
hi @tshinkle 
The message you pasted shows that it is trying to fetch that nuget package from your local machine.

xUnit runner package is available from nuget: https://www.nuget.org/packages/xunit.runner.visualstudio/ 

Have you changed the nuget configuration on any way ? or could it be a firewall that is preventing packages being fetch from the nuget source ?

**Comment by atoakley** [comment]
Closing this.  If it is still an issue, please reopen.
