### ISSUE TITLE
Error in command

### ISSUE THREAD

**Issue by ThierryBT** [mspnp/architecture-center#1183]
Hi and sorry for my English.
There is an error in the text (https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/secure-vnet-dmz)

In chapter "Deploy the solution", point 3.
It's impossible to launch 
azbb -s &lt;subscription_id&gt; -g &lt;resource_group_name&gt; -l &lt;region&gt; -p secure-vnet-hybrid.json --deploy

Because in point 1, you navigate to /dmz/secure-vnet-dmz.
Do you think it's possible to add a point between 2 and 3 for add :
Navigate to the /dmz/secure-vnet-hybrid folder of the reference architectures GitHub repository.

For information, it's the same error in French document (https://docs.microsoft.com/fr-fr/azure/architecture/reference-architectures/dmz/secure-vnet-dmz).

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 132f3909-1efc-e58a-7d58-8d378046f43a
* Version Independent ID: c94ad8d8-49c8-f47d-cf33-956f85b10ab1
* Content: [Implement a DMZ between Azure and the Internet - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/secure-vnet-dmz)
* Content Source: [docs/reference-architectures/dmz/secure-vnet-dmz.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/dmz/secure-vnet-dmz.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @ThierryBT Thank you for reporting this issue! We will review and make any necessary changes.
