### ISSUE TITLE
M33429: Link tags are impropery placed

### ISSUE THREAD

**Issue by v-makoud** [mspnp/architecture-center#1190]
Hello @tracsman, @telmosampaio, @miguelangelopereira,
Translator has reported possible source content issue.

Link to Github file: https://github.com/mspnp/architecture-center/blob/master/docs/vdc/networking-virtual-datacenter.md
Row where the issue is located: 102
String: With ExpressRoute Direct,]{1}ExRD{2} you can connect directly to Microsoft routers at 100 Gbps for customer with larger bandwidth needs.

Link to Github file: https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/n-tier/linux-vm.md
Row where the issue is located: 99
String: Use [Group Policy settings][group-policy] on the VM to enable automatic system updates.

Link to Github file: https://github.com/mspnp/architecture-center/blob/master/docs/example-scenario/infrastructure/linux-vdi-citrix.md
Row where the issue is located: 88
String: For more information, see [what are Availability Zones in Azure?][azureaz-docs].

Comment: Source error: The link tags are improperly placed. There are 3 parts in different files.

Can you please review the comment and provide answer/explanation? Also, if source fix is needed please provide link to the PR that will include the fix, so we can confirm and close this Issue.
Many thanks in advance.

**Comment by mike-urnun-msft** [comment]
Hi @v-makoud Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by v-maudel** [comment]
Thanks so much @mike-urnun-msft  and @MikeWasson
