### ISSUE TITLE
Image does not look good in dark theme.

### ISSUE THREAD

**Issue by slavizh** [mspnp/architecture-center#1201]
Image does not look good in dark theme.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c40dd77e-2034-abc1-0dfc-df4238bce00b
* Version Independent ID: e08ed609-a8f7-1c15-124f-79f958792153
* Content: [Building a cloud migration business case - Enterprise Cloud Adoption](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/business-strategy/cloud-migration-business-case)
* Content Source: [docs/cloud-adoption/business-strategy/cloud-migration-business-case.md](https://github.com/mspnp/architecture-center/blob/master/docs/cloud-adoption/business-strategy/cloud-migration-business-case.md)
* Service: **guidance**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @slavizh Thank you for reporting this issue! We will review and make any necessary changes.

**Comment by rotycenh** [comment]
Have created PR #1328 to remove any background transparencies that affect readability for images within the /cloud-adoption folder.
