### ISSUE TITLE
Dark mode image text legibility

### ISSUE THREAD

**Issue by PatMyron** [mspnp/architecture-center#1203]
This image: https://docs.microsoft.com/en-us/azure/architecture/aws-professional/images/azure-aws-account-compare.png on this page: https://docs.microsoft.com/en-us/azure/architecture/aws-professional/ is difficult to read in dark mode

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d100d43f-d48a-3d97-1aea-7a5409fdccc8
* Version Independent ID: 568dcd88-b93c-1d41-44d0-8643dd057a33
* Content: [Azure for AWS Professionals - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/)
* Content Source: [docs/aws-professional/index.md](https://github.com/mspnp/architecture-center/blob/master/docs/aws-professional/index.md)
* Service: **guidance**
* GitHub Login: @lbrader
* Microsoft Alias: **pnp**

**Comment by PatMyron** [comment]
related issues:

https://github.com/mspnp/architecture-center/issues/1202
https://github.com/mspnp/architecture-center/issues/958
https://github.com/mspnp/architecture-center/issues/545
https://github.com/mspnp/architecture-center/issues/1201
https://github.com/mspnp/architecture-center/issues/505

**Comment by mike-urnun-msft** [comment]
Hi @PatMyron Thank you for reporting this issue! We will review and make any necessary changes.

**Comment by ManuInNZ** [comment]
Hi there

same applies in the new section of Cloud Adoption Framework where some graphics are just unreadable or barely e.g. the [hierarchy of management groups and subscriptions](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/governance/journeys/small-to-medium-enterprise/overview#governance-best-practice) or [Future state](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/governance/journeys/small-to-medium-enterprise/narrative#future-state)

Some graphics have white background which would be a quick fix. Ideally there would be theme based graphics i.e. light and dark version.

This does not take away the fact that it is very good quality docs but just more easy to consume :).

Cheers
MAnu

**Comment by PatMyron** [comment]
@MikeWasson It looks like this problem could be more widespread than those two images: https://github.com/mspnp/architecture-center/pull/1328

I wrote a script using [ImageMagick](https://imagemagick.org/script/identify.php) to help find all of the images with transparent backgrounds:

```
~/Documents/GitHub/architecture-center $ for file in $(find . -name '*'); do

  if [[ $(identify -format '%[opaque]' $file 2>/dev/null) == False ]]; then echo $file; fi;

done
```

```
./docs/cloud-adoption/appendix/_images/components.png
./docs/cloud-adoption/_images/governance/process-metrics.png
./docs/cloud-adoption/_images/governance/design-guide.png
./docs/cloud-adoption/_images/governance/process-toolchain.png
./docs/cloud-adoption/_images/governance/policy-enforcement.png
./docs/cloud-adoption/_images/governance/enforcement.png
./docs/cloud-adoption/_images/governance/process-enforce.png
./docs/cloud-adoption/_images/governance/process-template.png
./docs/cloud-adoption/_images/governance/process-maturity.png
./docs/cloud-adoption/_images/governance/business-risk.png
./docs/cloud-adoption/_images/governance/corporate-policy.png
./docs/cloud-adoption/_images/governance/process-risks.png
./docs/patterns/_images/category-security.png
./docs/patterns/_images/category-design-implementation.png
./docs/patterns/_images/category-data-management.png
./docs/patterns/_images/category-availability.png
./docs/patterns/_images/category-performance-scalability.png
./docs/patterns/_images/category-messaging.png
./docs/patterns/_images/category-resiliency.png
./docs/patterns/_images/category-management-monitoring.png
./docs/reference-architectures/ai/_images/python-example-predictions.png
./docs/vdc/images/vdc-network.png
./docs/vdc/images/vdc-lift-and-shift.png
./docs/vdc/images/vdc-deck.png
./docs/_images/github.png
./docs/_images/icons/databricks.png
./docs/_images/icons/cognitive.png
./docs/best-practices/images/cdn/CDN.png
```

Hope this helps you guys identify all of the potential image legibility problems in dark mode!
