### ISSUE TITLE
Azure for Google Cloud Professionals

### ISSUE THREAD

**Issue by PatMyron** [mspnp/architecture-center#1204]
It would be nice to have similar pages for Google Cloud Platform as well

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/mspnp/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **guidance**
* GitHub Login: @lbrader
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @PatMyron Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by MikeWasson** [comment]
@PatMyron - Thanks for the suggestion. This isn't in our current roadmap, but we created a User Voice item for it [here][(https://azure-architecture.uservoice.com/forums/918127-general/suggestions/36654139-azure-guide-for-users-familiar-with-google-cloud) if you want to add your vote.
