### ISSUE TITLE
Service Fabric on Linux

### ISSUE THREAD

**Issue by waynemunro** [mspnp/architecture-center#1205]
Note that it is also possible to create Service Fabric clusters on Linux. see 
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-deploy-anywhere
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Decision tree for Azure compute services - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/mspnp/architecture-center/blob/master/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **guidance**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
@waynemunro Thanks for sharing! Surely, it'll benefit others visiting this thread!

We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
