### ISSUE TITLE
Sharding rename 

### ISSUE THREAD

**Issue by fcobo95** [mspnp/architecture-center#1206]
Hello,
Wanted to know what happens if I rename one of my shard? Will this break the sharding? Or what should I consider when renaming a shard?
Thanks in advanced!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 050bb1fd-56ca-63bc-b105-17a56e3b0362
* Version Independent ID: ce84d0a7-3596-e259-dfc3-a9789efd9948
* Content: [Sharding pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/sharding#example)
* Content Source: [docs/patterns/sharding.md](https://github.com/mspnp/architecture-center/blob/master/docs/patterns/sharding.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by dragon119** [comment]
@fcobo95 I'm not sure if I understand your question correctly but it's not easy to change the number of shards or mapping strategy (hash/range/map). What do you mean by renaming the shard? using which storage?

**Comment by mike-urnun-msft** [comment]
Hi @fcobo95 Since we haven't heard back, we will now proceed to close this thread for now. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
