### ISSUE TITLE
Subscription rules

### ISSUE THREAD

**Issue by dcbrown16** [mspnp/architecture-center#1213]
What are the length, casing, and valid characters (including positional restrictions like first and last character) for subscriptions?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @dcbrown16 Thank you for your feedback! We will review and update as appropriate.

**Comment by dcbrown16** [comment]
Thanks @KetanChawda-MSFT!
