### ISSUE TITLE
copy-paste error

### ISSUE THREAD

**Issue by andrePKI** [mspnp/architecture-center#1214]
In the last table, two rows are "Copy to relational database", one should read "from".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6e037b-a226-62cf-6e2b-2af8783b7add
* Version Independent ID: c666597e-52ae-ee51-474a-c4dd3a63941b
* Content: [Choosing a data transfer technology](https://docs.microsoft.com/en-us/azure/architecture/data-guide/scenarios/data-transfer)
* Content Source: [docs/data-guide/scenarios/data-transfer.md](https://github.com/mspnp/architecture-center/blob/master/docs/data-guide/scenarios/data-transfer.md)
* Service: **guidance**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @andrePKI Thank you for your feedback! We will review and update as appropriate.
