### ISSUE TITLE
Duplicate Section

### ISSUE THREAD

**Issue by JoeMcGrath** [mspnp/architecture-center#1221]
Under https://docs.microsoft.com/en-us/azure/architecture/vdc/networking-virtual-datacenter#component-type-perimeter-networks the Application Gateway description is duplicated - with the second description being a slightly altered version of the first

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d8a578-f9f1-53af-64d0-808f1fde6c9c
* Version Independent ID: 8a647cb7-2d10-53ed-5459-4356ef607e77
* Content: [Azure virtual datacenter: A network perspective](https://docs.microsoft.com/en-us/azure/architecture/vdc/networking-virtual-datacenter#component-type-perimeter-networks)
* Content Source: [docs/vdc/networking-virtual-datacenter.md](https://github.com/mspnp/architecture-center/blob/master/docs/vdc/networking-virtual-datacenter.md)
* Service: **architecture-center**
* GitHub Login: @tracsman
* Microsoft Alias: **jonor**

**Comment by MikeWasson** [comment]
Thanks - from Git history, the 1st paragraph is newer.
