### ISSUE TITLE
Scaffolding Image

### ISSUE THREAD

**Issue by AmitSheth** [mspnp/architecture-center#1236]
Should the "foundation" in the enterprise scaffolding image say "Management Groups" instead of "Subscription Groups"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdc23836-c10c-5c47-818b-42c53916b269
* Version Independent ID: b5ef4736-1df9-e3d9-eafb-7782cc0d5fea
* Content: [Best practices for enterprises moving to Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/appendix/azure-scaffold#feedback)
* Content Source: [docs/cloud-adoption/appendix/azure-scaffold.md](https://github.com/mspnp/architecture-center/blob/master/docs/cloud-adoption/appendix/azure-scaffold.md)
* Service: **architecture-center**
* GitHub Login: @rdendtler
* Microsoft Alias: **rodend**

**Comment by mike-urnun-msft** [comment]
Hi @AmitSheth Thank you for your feedback! We will review and update as appropriate.

**Comment by BrianBlanchard** [comment]
We are in the midst of repositioning this guidance to better align to a model that include management groups, subscriptions, and resource groups. This will be addressed in a coming release.
