### ISSUE TITLE
[typo]"heterogenous" should be "heterogeneous"

### ISSUE THREAD

**Issue by mkkb473** [mspnp/architecture-center#1239]
https://docs.microsoft.com/en-us/azure/architecture/patterns/sidecar#when-to-use-this-pattern
In "When to Use this Pattern" section, the first appeared "heterogenous" should be "heterogeneous".

**Comment by KetanChawda-MSFT** [comment]
@mkkb473 Thank you for your feedback! We will review and update as appropriate.

**Comment by KetanChawda-MSFT** [comment]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 500a87be-54d3-2c23-5a46-47e8163f30f9
* Version Independent ID: e69c1d3a-aebd-9def-3448-fe795bbf6327
* Content: [Sidecar pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/sidecar#when-to-use-this-pattern)
* Content Source: [docs/patterns/sidecar.md](https://github.com/mspnp/architecture-center/blob/master/docs/patterns/sidecar.md)
* Service: **architecture-center**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**
