### ISSUE TITLE
Composite SLA calculations for active/passive

### ISSUE THREAD

**Issue by amitgc** [mspnp/architecture-center#1242]
I have been reading the composite SLA calculation guidelines (https://github.com/mspnp/architecture-center/blob/master/docs/resiliency/index.md) and wanted to seek clarification on if the example refers to active/active or active/passive.

If you take an active/passive warm standby scenario and a 3 tier application, if one components fails and we need to fail over to the secondary region surely the formula applied would not be valid as some work is likely to be required to 'turn on' the passive instance. With assumed RTO and RPO values  is there a recommended formula for such a scenario?

**Comment by mike-urnun-msft** [comment]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 475fbe98-a5a8-7df3-9f9a-8e76f56aead8
* Version Independent ID: b9512213-b16d-a00a-7598-b78497eca2f6
* Content: [Designing resilient applications for Azure](https://docs.microsoft.com/en-us/azure/architecture/resiliency/)
* Content Source: [docs/resiliency/index.md](https://github.com/mspnp/architecture-center/blob/master/docs/resiliency/index.md)
* Service: **architecture-center**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@amitgc Thank you for the feedback. We will review and provide an update as appropriate.

**Comment by MikeWasson** [comment]
@amitgc Yes, you're correct. The SLA calculation tells you how likely it is that a system will fail in the critical path. Other factors can affect SLA or RTO/RPO. For example the article mentions:

> Failing over is not instantaneous in active-passive configurations, which can result in some downtime during a failover.

**Comment by amitgc** [comment]
So on reflection the guidance refers to active/active scenarios. As a passive system by its very nature is “down” until a manual steps is initiated to activate?

**Comment by KetanChawda-MSFT** [comment]
@amitgc checking in to see if the above post helped answering your question?

**Comment by mike-urnun-msft** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Comment by amitgc** [comment]
Hi - still a few questions but let me speak to the account team and get a dialogue going. It will be easier then pinging messages back and forth. Appreciate the help.

**Comment by amitgc** [comment]
> @amitgc Since we haven't heard back, we will now proceed to close this thread for now. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

Hi - still a few questions but let me speak to the account team and get a dialogue going. It will be easier then pinging messages back and forth. Appreciate the help.
