### ISSUE TITLE
Azure Redis Cache supports Redis clustering

### ISSUE THREAD

**Issue by ibayg** [mspnp/architecture-center#1249]
It's said "Azure Redis Cache does not currently support Redis clustering." this is wrong:
https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-how-to-premium-clustering

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef578ecf-7b41-cac8-ba5d-2e132c337b1e
* Version Independent ID: f325ab09-f55d-42ce-5892-a116d4958d6c
* Content: [Data partitioning strategies - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/data-partitioning-strategies)
* Content Source: [docs/best-practices/data-partitioning-strategies.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/data-partitioning-strategies.md)
* Service: **architecture-center**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @ibayg Thank you for reporting this issue! We will review and make any necessary changes.

**Comment by PramodValavala-MSFT** [comment]
@ibayg That is true. Do note that clustering is only available under the Premium SKU.

@MikeWasson Would you like me to work up a PR for this?
