### ISSUE TITLE
Azure Batch AI has migrated to Azure Machine Learning Compute

### ISSUE THREAD

**Issue by heatherbshapiro** [mspnp/architecture-center#1253]
Azure Batch AI is being retired and migrating to Azure Machine Learning Compute. https://docs.microsoft.com/en-us/azure/batch-ai/overview-what-happened-batch-ai 

The tutorial should be updated to use AML Compute instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aadc91ee-6255-a6fe-b2e1-42ca8eb88e85
* Version Independent ID: eb4c4b4f-f1d3-ebd5-fbb2-0c70237035a2
* Content: [Batch scoring for deep learning models - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/ai/batch-scoring-deep-learning)
* Content Source: [docs/reference-architectures/ai/batch-scoring-deep-learning.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/ai/batch-scoring-deep-learning.md)
* Service: **architecture-center**
* GitHub Login: @jiata
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hey @heatherbshapiro Thank you for reporting this issue! We will review and make any necessary changes.

**Comment by MikeWasson** [comment]
@heatherbshapiro Thanks for the feedback! We have an update to this doc that will be published later today.

**Comment by MikeWasson** [comment]
Update is
