### ISSUE TITLE
Tags allowed characters

### ISSUE THREAD

**Issue by dcbrown16** [mspnp/architecture-center#1256]
The example tag in the document itself is 
"sqlVersion"="sql2014ee"
yet the allowed characters for tags are listed as "Alphanumeric."
I wouldn't think alphanumeric includes " and =, but they do seem to work in a quick test.
Do the allowed characters need to be updated to something more accurate?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **architecture-center**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@dcbrown16 Thanks for your feedback. We will review this and provide an update as appropriate.

**Comment by KetanChawda-MSFT** [comment]
@dcbrown16 The following limitations apply to tags:

- Not all resource types support tags. To determine if you can apply a tag to a resource type, see [Tag support for Azure resources](https://docs.microsoft.com/en-us/azure/azure-resource-manager/tag-support).
- Each resource or resource group can have a maximum of 15 tag name/value pairs. This limitation applies only to tags directly applied to the resource group or resource. A resource group can contain many resources that each have 15 tag name/value pairs. If you have more than 15 values that you need to associate with a resource, use a JSON string for the tag value. The JSON string can contain many values that are applied to a single tag name. This article shows an example of assigning a JSON string to the tag.
- The tag `name` is limited to `512` characters, and the tag `value` is limited to `256` characters. For storage accounts, the tag name is limited to `128` characters, and the tag value is limited to `256` characters.
- Virtual Machines are limited to a total of `2048` characters for all tag names and values.
- Tags applied to the resource group are not inherited by the resources in that resource group.
- Tags can't be applied to classic resources such as Cloud Services.
- Tag names can't contain these characters: `<` `>` `%` `&` `\` `?` `/`

For details about Tags please refer the below document:
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-using-tags

I have created a referenced PR to update the document with appropriate details.

**Comment by KetanChawda-MSFT** [comment]
@dcbrown16 Thanks for the confirmation. We will now proceed to close this thread.
