### ISSUE TITLE
Figure 3 - explanation of caches is ambiguous

### ISSUE THREAD

**Issue by CodeRedPaul** [mspnp/architecture-center#1257]
The text explaining the logic of private vs shared cached in Figure 3 is ambiguous and contradictory. Within the context of the article, the precedence order that an application should use to retrieve data is private, shared, database. In the diagram however the explanation texts do not follow the same logic and begin, in the description of both the private and shared caches, that "if the shared cache service is unavailable...". Ultimately the description in Figure 3 proposes that if the shared cache is unavailable one should use the private cache, or if the shared cache is unavailable one should use the database. I believe that the description for the private cache ought to be more like, "If the private cache service is unavailable the application logic can retrieve data from the shared cache service."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be785717-ca5e-f3d6-8e60-4005d9503d08
* Version Independent ID: 3ce414e5-d923-0488-ff11-3aa8bd4c2d1e
* Content: [Caching guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/caching)
* Content Source: [docs/best-practices/caching.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/caching.md)
* Service: **architecture-center**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@CodeRedPaul It might seem a bit contradictory but that is because of this -
> However, there might be a scalability impact on the system if the application falls back to the original data store when the cache is temporarily unavailable. While the data store is being recovered, the original data store could be swamped with requests for data, resulting in timeouts and failed connections.
>
>Consider implementing a local, private cache in each instance of an application, together with the shared cache that all application instances access. When the application retrieves an item, it can check first in its local cache, then in the shared cache, and finally in the original data store. The local cache can be populated using the data in either the shared cache, or in the database if the shared cache is unavailable.
>
>This approach requires careful configuration to prevent the local cache from becoming too stale with respect to the shared cache. However, the local cache acts as a buffer if the shared cache is unreachable. Figure 3 shows this structure.

which is mentioned in the same section.

The Local Cache is (almost) always available since it resides in-memory in the same instance (and the same process too in most cases). So, local cache's availability is tied to the health of the instance itself.

> I say almost because I believe there might be a few cases where the local cache might be in a separate process (child or independent) which might become unavailable while the main process still runs

So, the diagram aims to describe the best way to staying resilient to failures and also not causing new failures by overloading the data store.

**Comment by PramodValavala-MSFT** [comment]
@CodeRedPaul Just following up here... Hope my previous comment clears things up.

**Comment by PramodValavala-MSFT** [comment]
@CodeRedPaul Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
