### ISSUE TITLE
Naming suggestion of tags

### ISSUE THREAD

**Issue by sujithq** [mspnp/architecture-center#1259]
In the **Deployment (CI/CD) considerations** section after the part where the build has succeeded in point 3 the current tag is **myrepo**.azurecr.io/delivery:v1.0.2 and the production tag is **reponame**.azurecr.io/prod/delivery:v1.0.2. I would be cleaner to use the same repo names: **myrepo** or **reponame**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5e2e444-d6b9-962e-56d4-8d1f3508ba9e
* Version Independent ID: 061ea6aa-353b-a98d-cbf6-639209a5fd1b
* Content: [Microservices architecture on Azure Kubernetes Service (AKS)](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/microservices/aks#security-considerations)
* Content Source: [docs/reference-architectures/microservices/aks.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/microservices/aks.md)
* Service: **architecture-center**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@sujithq Thank you posting your question. we will review this and provide an update as appropriate.

**Comment by MikeWasson** [comment]
@sujithq  Yes, thanks - that was the intent. I'll fix this.
