### ISSUE TITLE
loop-0 explanation

### ISSUE THREAD

**Issue by scott1138** [mspnp/architecture-center#1267]
Can you please provide more information on why loop-0 is needed?  Why can't the template creating the rules depend on NSG1 and eliminate loop-0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa870d42-1b00-d600-4fef-dd67219a1dc6
* Version Independent ID: 61fa68a5-a08b-7693-ebfd-18711ebd1bbb
* Content: [Use an object as a parameter in an Azure Resource Manager template](https://docs.microsoft.com/en-us/azure/architecture/building-blocks/extending-templates/objects-as-parameters)
* Content Source: [docs/building-blocks/extending-templates/objects-as-parameters.md](https://github.com/mspnp/architecture-center/blob/master/docs/building-blocks/extending-templates/objects-as-parameters.md)
* Service: **architecture-center**
* GitHub Login: @petertay
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@scott1138 To quote the doc
> Our second resource named loop-0 performs two functions: first, it `dependsOn` the NSG so its deployment doesn't begin until NSG1 is completed, and it is the first iteration of the sequential loop.

The keyword here is `sequential`.
If you were to set the `dependsOn` value to `NSG1` that would trigger all the `loop-*` deployments in parallel (by default). Hence, the `loop-0` resource and the line `"dependsOn": ["[concat('loop-', copyIndex())]"]` to make the deployments sequential.

That being said, I believe since this doc was first published, there is now a **_serial mode_** for iterations as described at the end of [this](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-multiple#resource-iteration) section which can be used here.

With `mode` set to `Serial`, the `loop-*` resource deployments can be avoided and the template would be simplified to something like this
```json
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "networkSecurityGroupsSettings": { "type": "object" }
  },
  "variables": {},
  "resources": [
    {
      "apiVersion": "2015-06-15",
      "type": "Microsoft.Network/networkSecurityGroups",
      "name": "NSG1",
      "location": "[resourceGroup().location]",
      "properties": {
        "securityRules": []
      }
    },
    {
      "name": "[concat('NSG1/' , parameters('networkSecurityGroupsSettings').securityRules[copyIndex()].name)]",
      "type": "Microsoft.Network/networkSecurityGroups/securityRules",
      "apiVersion": "2016-09-01",
      "location": "[resourceGroup().location]",
      "properties": {
        "description": "[parameters('networkSecurityGroupsSettings').securityRules[copyIndex()].description]",
        "priority": "[parameters('networkSecurityGroupsSettings').securityRules[copyIndex()].priority]",
        "protocol": "[parameters('networkSecurityGroupsSettings').securityRules[copyIndex()].protocol]",
        "sourcePortRange": "[parameters('networkSecurityGroupsSettings').securityRules[copyIndex()].sourcePortRange]",
        "destinationPortRange": "[parameters('networkSecurityGroupsSettings').securityRules[copyIndex()].destinationPortRange]",
        "sourceAddressPrefix": "[parameters('networkSecurityGroupsSettings').securityRules[copyIndex()].sourceAddressPrefix]",
        "destinationAddressPrefix": "[parameters('networkSecurityGroupsSettings').securityRules[copyIndex()].destinationAddressPrefix]",
        "access": "[parameters('networkSecurityGroupsSettings').securityRules[copyIndex()].access]",
        "direction": "[parameters('networkSecurityGroupsSettings').securityRules[copyIndex()].direction]"
      },
      "copy": {
        "name": "securityRulesCopy",
        "count": "[length(parameters('networkSecurityGroupsSettings').securityRules)]",
        "mode": "Serial",
        "batchSize": 1
      }
    }
  ],
  "outputs": {}
}
```

**Comment by PramodValavala-MSFT** [comment]
@scott1138 Just following up here... Hope my previous comment helps.

**Comment by scott1138** [comment]
Sorry for not replying sooner!  It does make sense now.  By executing loop-0 outside of the last resource and then using copyindex(1) for the new loop name and copyindex() as the dependson the loops are dependent on the previous loop.  Guess I should have thought about it a little harder!

Regards,

Scott Heath

Lead DevOps Engineer

t 1 214 445 1441<tel:+1%20214%20445%201441> | m 1 972 273 0752 | <tel:+1%20972%20273%200752> freeman.com<http://freeman.com/>

**Comment by PramodValavala-MSFT** [comment]
@scott1138 Glad we could help! 😄 

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
