### ISSUE TITLE
Integrating with Azure Blueprints

### ISSUE THREAD

**Issue by kazshi** [mspnp/architecture-center#1271]
Is it possible to integrate DevOps with Blueprints (or Blueprints with DevOps?)? For example, deploying Web App application using DevOps into App Service in a resource group defined/deployed by Blueprints.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8865190-b9ac-ae5e-2590-30237ed43697
* Version Independent ID: 45d8bb8c-10f1-de72-6644-a20ba60a32af
* Content: [Design a CI/CD pipeline using Azure DevOps - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/devops-dotnet-webapp)
* Content Source: [docs/example-scenario/apps/devops-dotnet-webapp.md](https://github.com/mspnp/architecture-center/blob/master/docs/example-scenario/apps/devops-dotnet-webapp.md)
* Service: **architecture-center**
* GitHub Login: @christianreddington
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@kazshi Thank you for posting question. The intent of this document is to provide architecture and design guidance for building a continuous integration (CI) and continuous deployment (CD) pipeline to deploy a two-tier .NET web application to the Azure App Service.

This question looks more of a `Azure Blueprints` question which is outside the scope of this document. I will encourage you to check the [referenced issue](https://github.com/MicrosoftDocs/azure-docs/issues/18389) if that helps else you can ask this question on [this document](https://docs.microsoft.com/en-in/azure/governance/blueprints/overview) to be answer by the correct team.

With that said, we will now proceed to close this thread. If there are further questions regarding this document, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by kazshi** [comment]
@KetanChawda-MSFT You're' right. Thanks for your comment.
