### ISSUE TITLE
Manageability Considerations  - Shutting Down a DC using Azure Portal

### ISSUE THREAD

**Issue by Dagriff** [mspnp/architecture-center#1277]
Does this warning also apply to a warm restart invoked through the portal?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Extend Active Directory Domain Services (AD DS) to Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/identity/adds-extend-domain.md)
* Service: **architecture-center**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@Dagriff Nope. A `restart` from the portal doesn't have the same implications.

The warning is necessary because the [`deallocate`](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/deallocate) API is called when shutting down a VM from the portal.

**Comment by KbLev** [comment]
What about shutting down the VM from the OS and _then_ deallocating the box on the portal to save cost?

**Comment by PramodValavala-MSFT** [comment]
@Dagriff Its similar to directly shutting down from the portal or call the deallocate API.

This would create the same situation mentioned in the docs - 
> Shutting down through the portal causes the VM to be deallocated, which resets both the `VM-GenerationID` and the `invocationID` of the Active Directory repository. This discards the AD DS relative identifier (RID) pool and marks SYSVOL as nonauthoritative, and may require reconfiguration of the domain controller.

**Comment by PramodValavala-MSFT** [comment]
@Dagriff Just following up here... I hope my previous comment clears things up.

**Comment by PramodValavala-MSFT** [comment]
@Dagriff Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
