### ISSUE TITLE
Azure Container Service

### ISSUE THREAD

**Issue by ryancrawcour** [mspnp/architecture-center#1280]
This document still references Azure Container Services, and doesn't seem to mention AKS anywhere.
It also still mentions Cloud Services, which I do not believe are available anymore, at least not for new workloads. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0d64006-a818-b7fe-7245-bcdba08434cc
* Version Independent ID: 13ac8881-39c6-b3c1-cfe8-58ff4c9c19cd
* Content: [Overview of Azure compute options - Azure Application Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-overview#feedback)
* Content Source: [docs/guide/technology-choices/compute-overview.md](https://github.com/mspnp/architecture-center/blob/master/docs/guide/technology-choices/compute-overview.md)
* Service: **architecture-center**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@ryancrawcour Thanks for the feedback! We have assigned this issue to the content author to review and update accordingly.

**Comment by cbailiss** [comment]
I have used Cloud Services for several years.
Cloud Services are still available and can be created for new services.
I have seen Cloud Services referred to as legacy, which they are, but have not seen any official deprecation notice or end of life deadline.
Particularly for the worker role, I don't see a close like-for-like replacement.  Service Fabric is more complex and has a notably higher minimum cluster size for production workloads (=significantly more expensive).  Container Instances, for long running workloads, are also very expensive.
Being forced to migrate to VMs feels like the closest option today, but I'd rather use a PaaS option than IaaS.
The fact that Cloud Services were ported to ARM from ASM suggests they have a bit of life left in them yet.
Having said all that, if Microsoft are getting close to deprecating them it would be great to know that, and also what the replacement is at similar cost and complexity points.
