### ISSUE TITLE
Staging of data

### ISSUE THREAD

**Issue by Datapipes** [mspnp/architecture-center#1281]
Not sure I get how the data is stored in blob storage from the On-prem database. Usually you want persist data in a staging environment and write a SQL merge when doing delta loads from a source database. Is that done via polybase into the integration schema? Would had been nice to have that part more documented when putting out an reference architecture. Thanks.

**Comment by PramodValavala-MSFT** [comment]
@Datapipes Could you share which doc you were referring to?

**Comment by Datapipes** [comment]
It was this doc: https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/enterprise-bi-adf 

But I can see now that it is building on top of:
https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/enterprise-bi-sqldw

So now it makes sense ;-)
