### ISSUE TITLE
AWS has a backup solution AWS Backup

### ISSUE THREAD

**Issue by mchudinov** [mspnp/architecture-center#1286]
AWS has a backup solution called AWS Backup. Update the document please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [AWS to Azure services comparison - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/mspnp/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **architecture-center**
* GitHub Login: @lbrader
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @mchudinov Thank you for your feedback! We will review and update as appropriate.
