### ISSUE TITLE
Grammar and formatting

### ISSUE THREAD

**Issue by richardspitz** [mspnp/architecture-center#1291]
"Respond to failures" section: 
Failover:
1. Configure a disaster recovery strategy your application -> Configure a disaster recovery strategy for your application
2. For more scenarous -> For most scenarios

Operational readiness testing:
1. Alternatevely -> Alternatively

Data consistency check:
1. For example, Geo-redundant storage) and Key Vault follow this model -> For example, Geo-redundant storage and Key Vault follow this model

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 475fbe98-a5a8-7df3-9f9a-8e76f56aead8
* Version Independent ID: b9512213-b16d-a00a-7598-b78497eca2f6
* Content: [Designing resilient applications for Azure](https://docs.microsoft.com/en-us/azure/architecture/resiliency/)
* Content Source: [docs/resiliency/index.md](https://github.com/mspnp/architecture-center/blob/master/docs/resiliency/index.md)
* Service: **architecture-center**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@richardspitz Thanks for the feedback! If you'd like, you could make the edits and contribute to the docs as well. 😄

Here is the [Contributor Guide](https://docs.microsoft.com/en-us/contribute/) that you can refer to if you plan to contribute.
