### ISSUE TITLE
Issue with 'Implement a DMZ between Azure and the Internet' deployment guide 

### ISSUE THREAD

**Issue by asahire** [mspnp/architecture-center#1299]
pub-dmz-lb resource is not getting created with above mentioned steps. 

Looks like, following Instructions are the culprit.
3. Navigate to the /dmz/ssecure-vnet-hybrid folder of the reference architectures GitHub repository.
4. Run the following command:
azbb -s <subscription_id> -g <resource_group_name> -l <region> -p secure-vnet-hybrid.json --deploy

We need to use 'secure-vnet-dmz.json' instead of 'secure-vnet-hybrid.json' from '/dmz/secure-vnet-dmz' Repo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 132f3909-1efc-e58a-7d58-8d378046f43a
* Version Independent ID: c94ad8d8-49c8-f47d-cf33-956f85b10ab1
* Content: [Implement a DMZ between Azure and the Internet - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/secure-vnet-dmz)
* Content Source: [docs/reference-architectures/dmz/secure-vnet-dmz.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/dmz/secure-vnet-dmz.md)
* Service: **architecture-center**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@asahire Thanks for catching that! You are right about the discrepancy.

I will work up a PR for fixing this.
