### ISSUE TITLE
Naming rules and restrictions for resource group seems can not apply to resource group that Azure SignalR Service is created within

### ISSUE THREAD

**Issue by FredHan001** [mspnp/architecture-center#1305]
In [documentation](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions), the "Naming rules and restrictions" for a resource group could be **1-90** length, but when we create SignalR Service on Azure portal, we can find the Azure portal use a special validation rule to valid Resource group.

***It must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character. 
The value must be between 3 and 63 characters long.***

Not sure if it is a content issue or Azure portal issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **architecture-center**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@FredHan001 Thank you for the feedback. We will review this and provide an update as appropriate.

**Comment by KetanChawda-MSFT** [comment]
@FredHan001 The naming rules and restrictions for SignalR service is more strict than other Azure Services due to some product requirements. I understand this is not consistent with Azure standard, but for now you have to make the resource group name within 3-63 letters and it should work for most of the customers.

We have an internal work item in place to document this service specific naming restrictions but as of now I don't have any ETA on that when it will publish.

**Comment by KetanChawda-MSFT** [comment]
@FredHan001 We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
