### ISSUE TITLE
M35533: Missing link

### ISSUE THREAD

**Issue by v-makoud** [mspnp/architecture-center#1306]
Hello @BrianBlanchard,
Translator has reported possible source content issue.
Link to Github file: https://github.com/mspnp/architecture-center/blob/master/docs/cloud-adoption/governance/policy-compliance/risk-tolerance.md
Row where the issue is located: 26
Comment: "[Cost Management]" should be link text, but link is missing.

Can you please review the comment and provide answer/explanation? Also, if source fix is needed please provide link to the PR that will include the fix, so we can confirm and close this Issue.
Many thanks in advance.

**Comment by KetanChawda-MSFT** [comment]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5f29b9b-7da2-3f4a-af75-4f8d91d886f7
* Version Independent ID: 38c3d371-98d7-b866-74e3-a1c2654cfcef
* Content: [CAF: What business risks are associated with a Cloud Transformation?](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/governance/policy-compliance/risk-tolerance)
* Content Source: [docs/cloud-adoption/governance/policy-compliance/risk-tolerance.md](https://github.com/mspnp/architecture-center/blob/master/docs/cloud-adoption/governance/policy-compliance/risk-tolerance.md)
* Service: **guidance**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **pnp**
---

@v-makoud Thank you for the feedback. We will review this and provide an update as appropriate.
