### ISSUE TITLE
Typo in Code Example under "Using Redis Caching"

### ISSUE THREAD

**Issue by timmyreilly** [mspnp/architecture-center#1309]
Small typo in code sample: 
```csharp
    // Now do the inverse so we can figure how which blog posts have a given tag
```

This is under the 'Using Redis Caching' section. 
Happy to submit a pr... 
I think it should be:

```csharp
  // Now do the inverse so we can figure out which blog posts have a given tag
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be785717-ca5e-f3d6-8e60-4005d9503d08
* Version Independent ID: 3ce414e5-d923-0488-ff11-3aa8bd4c2d1e
* Content: [Caching guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/caching)
* Content Source: [docs/best-practices/caching.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/caching.md)
* Service: **architecture-center**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@timmyreilly Thank you for the feedback and PR. The doc will be update with the PR you created.

**Comment by KetanChawda-MSFT** [comment]
@timmyreilly Doc has been updated. Thanks for your inputs.
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
