### ISSUE TITLE
SSL proxy for Redis required

### ISSUE THREAD

**Issue by fbodmer** [mspnp/architecture-center#1314]
The text states:
'If you need to protect data as it flows across the network, we recommend implementing an SSL proxy.'

Redis supports access using SSL. How is above statement to be understood?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be785717-ca5e-f3d6-8e60-4005d9503d08
* Version Independent ID: 3ce414e5-d923-0488-ff11-3aa8bd4c2d1e
* Content: [Caching guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/caching#considerations-for-implementing-caching-in-azure)
* Content Source: [docs/best-practices/caching.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/caching.md)
* Service: **architecture-center**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@fbodmer Those lines are actually the exact same ones from the [official redis docs](https://redis.io/topics/security#data-encryption-support).

Redis doesn't provide encryption on its own as mentioned [here](https://redis.io/topics/encryption) and recommends using a [SSL tunnel of sorts](http://www.tarsnap.com/spiped.html).
But Azure Redis Cache does support SSL as mentioned a few lines later.

**Comment by PramodValavala-MSFT** [comment]
@fbodmer Also, do note the [section](https://docs.microsoft.com/en-us/azure/architecture/best-practices/caching#redis-security) up until that line is actually talking just about redis in general and the [section](https://docs.microsoft.com/en-us/azure/architecture/best-practices/caching#azure-redis-cache) following it talks about Azure Redis Cache, the service offering in Azure.

This doc is part Azure Architecture Center which is a set of docs explaining best practices in general and then try touching on what Azure provides to achieve them.

Hope that clears things up.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
