### ISSUE TITLE
SQL Server Always On Availability Groups: Broken Link

### ISSUE THREAD

**Issue by RCormier-MSFT** [mspnp/architecture-center#1315]
The more information link 'Create the availability group and add the SharePoint databases' currently points to:
'https//docs.microsoft.com/SharePoint/administration/sharepoint-intranet-farm-in-azure-phase-5-create-the-availability-group-and-add' 

(missing colon after https, resulting in a broken link). 

Should be updated to:
'https://docs.microsoft.com/SharePoint/administration/sharepoint-intranet-farm-in-azure-phase-5-create-the-availability-group-and-add'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d93eb87-54cb-cf38-dfae-0ebe7579d608
* Version Independent ID: c7ac665e-d194-ab07-c1bb-5d5a3049c5ec
* Content: [Run a highly available SharePoint Server 2016 farm in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/)
* Content Source: [docs/reference-architectures/sharepoint/index.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/sharepoint/index.md)
* Service: **architecture-center**
* GitHub Login: @njray
* Microsoft Alias: **pnp**

**Comment by RCormier-MSFT** [comment]
This issue does not appear to be a problem with the structure of the link referenced in the markdown, but rather an issue with the permalink itself being broken:
https://technet.microsoft.com/library/mt793548(v=office.16).aspx

**Comment by Mike-Ubezzi-MSFT** [comment]
@RCormier-MSFT Thank you for taking the time to detail these minor but annoying link issue. Can you provide the source page where the link needs to be fixed? I see the corrected link but I no detail as to the source page where the link needs to be addressed. Thank you!

**Comment by RCormier-MSFT** [comment]
Sure thing, the link is on this page:
https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/

**Comment by mike-urnun-msft** [comment]
@RCormier-MSFT Thanks again for reporting this issue! We will review and make any necessary changes.

**Comment by Mike-Ubezzi-MSFT** [comment]
@njray for awareness.

**Comment by KetanChawda-MSFT** [comment]
@MikeWasson Can we add a direct link [https://docs.microsoft.com/en-us/SharePoint/administration/sharepoint-intranet-farm-in-azure-phase-5-create-the-availability-group-and-add](https://docs.microsoft.com/en-us/SharePoint/administration/sharepoint-intranet-farm-in-azure-phase-5-create-the-availability-group-and-add) in the doc instead of technet link 
[https://technet.microsoft.com/library/mt793548(v=office.16).aspx](https://technet.microsoft.com/library/mt793548(v=office.16).aspx) ?

**Comment by KetanChawda-MSFT** [comment]
@RCormier-MSFT Thank you for reporting this out. Referenced [PR#1325](https://github.com/mspnp/architecture-center/pull/1325) will fix the broken link in the doc

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
