### ISSUE TITLE
how can I run this application without AAD

### ISSUE THREAD

**Issue by mathewspjacob** [mspnp/architecture-center#1332]
[Enter feedback here]

Sir, how can I run this application without AAD. Can you please help me.d
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 059ca2fe-51fb-9226-6669-c4001c8bc8b8
* Version Independent ID: 982fc74f-5fc1-55a0-ba94-711b07430364
* Content: [Run the Surveys application](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/run-the-app)
* Content Source: [docs/multitenant-identity/run-the-app.md](https://github.com/mspnp/architecture-center/blob/master/docs/multitenant-identity/run-the-app.md)
* Service: **architecture-center**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@mathewspjacob Thank you posting your question. The intent of the documents is to explain how to manage user identities in a multitenant SaaS application on Microsoft Azure, using Azure Active Directory for authentication. however the application code is open source and available at [GitHub repo.](https://github.com/mspnp/multitenant-saas-guidance) you can download the code and modify it as per your requirement.

PS: This repo is meant for the feedback regarding document.

**Comment by KetanChawda-MSFT** [comment]
@mathewspjacob Since there is no doc update required at the moment, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
