### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by steve-hawkins** [mspnp/architecture-center#1334]
Firstly great document.  I have a few other question I will post separately, but there is a typo that is bothering me:-

Under - [Failure of a dependent service](https://docs.microsoft.com/en-us/azure/architecture/resiliency/disaster-recovery-azure-applications#failure-of-a-dependent-service)

> Note that high availability decreases throughput and increases latency because write operations must also `upedate` any secondary copies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cefa78da-afbb-5529-d707-b158d991cb16
* Version Independent ID: 64342775-2746-0e51-9aba-253074530f27
* Content: [Disaster recovery for Azure applications](https://docs.microsoft.com/en-us/azure/architecture/resiliency/disaster-recovery-azure-applications)
* Content Source: [docs/resiliency/disaster-recovery-azure-applications.md](https://github.com/mspnp/architecture-center/blob/master/docs/resiliency/disaster-recovery-azure-applications.md)
* Service: **architecture-center**
* GitHub Login: @adamglick
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Thanks for reporting this!
