### ISSUE TITLE
checklist structuring

### ISSUE THREAD

**Issue by bennage** [mspnp/architecture-center#15]
See original request:
https://github.com/mspnp/elasticsearch/issues/65
---
Possibly it is worthwhile to re-structure the list to a table creating a checklist that can be actionable. Table columns: tick (checked/unchecked), item (what we have in bold), description (what we have after bold text)

**Comment by MikeWasson** [comment]
That's an interesting idea for something like a PDF layout (for printing). 

In practice, only very simple table formats work well in the current site CSS for the online version.
