### ISSUE TITLE
Examples in docs/building-blocks/extending-templates/collector.md is inconsistent with variable names.

### ISSUE THREAD

**Issue by leftler** [mspnp/architecture-center#239]
in https://github.com/mspnp/architecture-center/blob/master/docs/building-blocks/extending-templates/collector.md the code examples use inconsistent values for the names of objects and variables.

For example, the first two lines below explicitly say the variable's name is `collectorTemplateUri` but the code uses `"uri": "[variables('linkedTemplateUri')]"` in the 2nd code example.

> Next, our template defines a single variable named `collectorTemplateUri`:
> 
> ```json
> "variables": {
>     "collectorTemplateUri": "[uri(deployment().properties.templateLink.uri, 'collector.template.json')]"
>   }
> ```
> 
> As you would expect, this is the URI for the **collector template** that will be used by our linked template resource:
> 
> ```json
> {
>     "apiVersion": "2015-01-01",
>     "name": "collector",
>     "type": "Microsoft.Resources/deployments",
>     "properties": {
>         "mode": "Incremental",
>         "templateLink": {
>             "uri": "[variables('linkedTemplateUri')]",
>             "contentVersion": "1.0.0.0"
>         },
>         "parameters": {
>             "source" : {"value": "[parameters('networkSecurityGroupsSettings').securityRules]"},
>             "transformTemplateUri": { "value": "[uri(deployment().properties.templateLink.uri, 'transform.json')]"}
>         }
>     }
> }
> ```

Another example is in the last code snippit, there is no resource declared named `firstResource` anywhere in the guide before this point, is this meant to be `reference('collector').outputs.result.value`?

> 
> Finally, our `Microsoft.Network/networkSecurityGroups` resource directly assigns the `output` of the `collector` linked template resource to its `securityRules` property:
> 
> ```json
>     {
>       "apiVersion": "2015-06-15",
>       "type": "Microsoft.Network/networkSecurityGroups",
>       "name": "networkSecurityGroup1",
>       "location": "[resourceGroup().location]",
>       "properties": {
>         "securityRules": "[reference('firstResource').outputs.result.value]"
>       }
>     }
>   ],
>   "outputs": {
>       "instance":{
>           "type": "array",
>           "value": "[reference('firstResource').outputs.result.value]"
>       }
> 
>   }
> ```

**Comment by Petertaylor9999** [comment]
The document is correct - you can see a working implementation here: https://github.com/jeffpatton1971/arm-property-transform-collector/tree/v1.1
