### ISSUE TITLE
Document says that subnets should be in resource groups

### ISSUE THREAD

**Issue by MikaVirkkunen** [mspnp/architecture-center#257]
Document says that subnets should be in resource groups but instead it's the VM which is in RG, not those subnets.

**Comment by MikeWasson** [comment]
Can you specify which article this is about? Thanks!

**Comment by MikaVirkkunen** [comment]
It's this one: https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/secure-vnet-hybrid and this section: "We recommend creating the following resource groups:"
Also the picture is missing some arrows at the DB tier from the LB. It seems to be bug in that visio doc.

**Comment by MikeWasson** [comment]
Thanks - this should refer to the VNet, not the subnets. We'll update the doc.

Regarding the diagram, I believe the 3rd VM is supposed to be the File Share Watcher although that's not really clear. 😸
