### ISSUE TITLE
Add list of Reserved Words for Azure Resources

### ISSUE THREAD

**Issue by axelgMS** [mspnp/architecture-center#285]
CRI 50012373
Can we add a list of Reserved Words (_ie. that can't be used by customers_) for Azure Resources ?
eg. "**loginstorage**" can't be used as a Storage Account - as it contains "**login**" which is reserved.
There are others like "**Microsoft**", "**Windows**", "**XBOX**"....
Having a public version of that list would help deflecting cases opened at CSS.
Thanks

**Comment by MikeWasson** [comment]
This issue should probably be opened against the Resource Manager docs.
