### ISSUE TITLE
Incorrect maximum value specified for "MaximumExecutionTime"

### ISSUE THREAD

**Issue by Diastro** [mspnp/architecture-center#311]
Hi,

On this [page](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/retry-service-specific.md) one of the code snippet state that the maximum possible value for "MaximumExecutionTime" is 10 seconds but later in the specification table the default stated value is 120 seconds (which doesn't seem to be consistent).

Looking in the [source code](https://github.com/Azure/azure-storage-net/blob/bdeb107c5fc1ad6db84fe6deaff17b15717aac0c/Lib/AspNet/Microsoft.WindowsAzure.Storage.Facade/FacadeLib/Microsoft.WindowsAzure.Storage.Shared.Protocol.Constants.cs#L6) it seems like the maximum value is 24 days.

Thanks,

**Comment by MikeWasson** [comment]
Yeah, the comment in the code snippet is ambiguous. We'll update this doc. thanks!
