### ISSUE TITLE
mistake in hub-vnet.json 

### ISSUE THREAD

**Issue by hadr10** [mspnp/architecture-center#458]
Hello,

in hub-vnet.json there is a mistake (script cannot create network interface, because cannot find virtual network, it tries to make it in the resource group where is VM), you need to add ResourceGroupName parameter for virtual network in row 44. So it will be:
"virtualNetwork": {
                            "name": "hub-vnet",
                            "resourceGroupName": "hub-vnet-rg"
                        }

Honza

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Implementing a hub-spoke network topology in Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke#feedback)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Thanks for reporting this. We're currently reviewing all of the deployment scripts.

**Comment by MikeWasson** [comment]
Hi - we recently updated the deployment template for this architecture. I've tested the updated version, but let us know if you still have issues. Thanks!
