### ISSUE TITLE
Where is Application Gateway?

### ISSUE THREAD

**Issue by ohwellwhatever** [mspnp/architecture-center#463]
Would like to see this updated to include Application Gateway as an important security component similar to https://blog.nilayparikh.com/azure/services/cloud-architecture-pattern-azure-service-fabric-and-microservices-part-2-logical-architecture/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78a7e7bd-23f3-a39f-9015-b77f14bb43e5
* Version Independent ID: 0ac34e7e-315f-2452-bf0a-74e9b1068c38
* Content: [Microservices architecture style](https://docs.microsoft.com/en-us/azure/architecture/guide/architecture-styles/microservices)
* Content Source: [docs/guide/architecture-styles/microservices.md](https://github.com/mspnp/architecture-center/blob/master/docs/guide/architecture-styles/microservices.md)
* Service: **guidance**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by yscontrol** [comment]
I think it would be helpful to create Quick-start section for microservices and API GW  similar to Web App Quick-start

**Comment by MikeWasson** [comment]
Thanks for the feedback. Our microservices design guide does mention App Gateway in the section on [gateways](https://docs.microsoft.com/en-us/azure/architecture/microservices/gateway#choosing-a-gateway-technology). The "architectural style" doc is not meant to be a comprehensive implementation guide. 

Reference architectures for microservices are on our backlog.
