### ISSUE TITLE
SAP: managed disks

### ISSUE THREAD

**Issue by amitlalaawaz** [mspnp/architecture-center#465]
Great starter pack and step by step guide..Any info on managed disks template availability? Thanks,
Amit Lal 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39c41519-edbf-79e8-0799-bf31a147f683
* Version Independent ID: 63f41e62-235f-c803-b1e5-5c427d3a7f5a
* Content: [Deploy SAP NetWeaver and SAP HANA on Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/sap/index)
* Content Source: [docs/reference-architectures/sap/index.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/sap/index.md)
* Service: **guidance**
* GitHub Login: @njray
* Microsoft Alias: **pnp**

**Comment by dragon119** [comment]
We're going to deprecate that template. We're working on newer ones which will be published on Quick starts gallery.
