### ISSUE TITLE
New Slick and Animated Icons

### ISSUE THREAD

**Issue by dsushil2000** [mspnp/architecture-center#469]
Dear Team, Can I get the Icons used in following presentations. They are animated and looks really nice in order to present the concepts.
https://azure.microsoft.com/en-us/resources/videos/an-overview-of-azure-event-grid/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20f420e0-251f-3b3b-75e6-6d6fb1cfd7b7
* Version Independent ID: 1b2c9022-af0b-e6f3-92fc-f3253ebc965d
* Content: [Icons and other assets for architectual diagrams](https://docs.microsoft.com/en-us/azure/architecture/resources/diagrams)
* Content Source: [docs/resources/diagrams.md](https://github.com/mspnp/architecture-center/blob/master/docs/resources/diagrams.md)
* Service: **guidance**
* GitHub Login: @bennage
* Microsoft Alias: **pnp**

**Comment by banisadr** [comment]
Unfortunately, the diagrams aren't currently available to be shared publicly

**Comment by bennage** [comment]
Thanks @banisadr.
