### ISSUE TITLE
Custom implementation of TokenCache always deserializes refreshToken as null

### ISSUE THREAD

**Issue by michaelsrichter** [mspnp/architecture-center#480]
Hi, looking for help or guidance on this topic: 

We are currently using ADAL for .Net V3.  ADAL V3 hides the Refresh Token.  While developing our own implementation of the TokenCache, I noticed when serializing/deserializing the class that the refresh token is always set to NULL.    According to this blog http://www.cloudidentity.com/blog/2015/08/13/adal-3-didnt-return-refresh-tokens-for-5-months-and-nobody-noticed, it isn’t needed.  I’m concerned this isn’t true in a multi-server environment with load balancing, where in-memory caching won’t work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab204a8d-c451-ef99-6610-139a0dee61ac
* Version Independent ID: 23a69ae2-70bc-aab5-bbe1-e9699d57558b
* Content: [Cache acess tokens in a multitenant application](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/token-cache)
* Content Source: [docs/multitenant-identity/token-cache.md](https://github.com/mspnp/architecture-center/blob/master/docs/multitenant-identity/token-cache.md)
* Service: **guidance**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Note sure why the refresh token is null, but my understanding is that it shouldn't matter. In general though in-memory caching won't work across load-balanced servers, a distributed token cache should using a backing store such as Redis.
