### ISSUE TITLE
Naming Rules and Restrictions seems incomplete

### ISSUE THREAD

**Issue by andyjballgit** [mspnp/architecture-center#502]
for example no details on Action Groups / Alerts from Azure Monitor

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources](https://docs.microsoft.com/en-gb/azure/architecture/best-practices/naming-conventions)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by ShaneCourtrille** [comment]
Or App services or Cloud Services or a lot of things..

**Comment by MikeWasson** [comment]
Yes, that's true. Primarily this topic is meant as guidance on creating a set of naming conventions for your organization. It doesn't document every service's naming rules.

**Comment by tjrobinson** [comment]
@MikeWasson That is a fair point, though it would be very useful if the "Naming rules and restrictions" section covered all available services.

**Comment by ShaneCourtrille** [comment]
Or at least enough services in each area that we could generalize ourselves.  As is it's too small of a sample AND there isn't any explanation for why one example does one thing and another doesn't (inclusion of environment for instance is a good example).  My best guess is that it's the common UI that the name will be seen in which drives things but who knows.
