### ISSUE TITLE
Should the client retry for the 429 response code

### ISSUE THREAD

**Issue by bingosummer** [mspnp/architecture-center#503]
The response code 429 means a throttling error. The client should retry. This should be documented in the "general REST and retry guidelines" and "Azure Active Directory retry guidelines".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Retry service specific guidance](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#general-rest-and-retry-guidelines)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/retry-service-specific.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by dragon119** [comment]
@bingosummer Thank you for your feedback. I agree that we should add them to the guidance. We'll update the content very soon.
