### ISSUE TITLE
Feedback on compute decision tree

### ISSUE THREAD

**Issue by manjnath** [mspnp/architecture-center#505]
Thoughts on the decision tree

2 Thoughts. (1). What is the defination of "portability"? VMSS are not necessarily "portable", as for example, Containers could be. (2). Can you please change the color of the text labels so it renders properly in the Dark theme and make the Start button stand out a bit - the eyes go to the dark blue boxes right away. Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Decision tree for Azure compute services](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/mspnp/architecture-center/blob/master/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **guidance**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Thanks for the feedback.

Regarding portability: Not all workloads can or should be containerized, and you can also run containers on VMs. Scale sets provide some management functionality, but the image that you deploy to a scale set should be portable regardless. And, you can deploy VMs without using scale sets, if desired. 

Regarding the color scheme, I opened a PR to address this. #514
