### ISSUE TITLE
ENOENT: no such file or directory, open '...../architecture-center/docs/index.yml'

### ISSUE THREAD

**Issue by abossard** [mspnp/architecture-center#51]
I can't find the index.yml and thus can't build the documentation.

**Comment by bennage** [comment]
Yes, we accidentally broke this during a hasty effort to come into compliance with publishing platform. 
There are actually a couple of things broken with the build scripts. We will fix it, but we have a couple of other high priority items that are taking our attention. 
I anticipate getting to this in early May.

**Comment by abossard** [comment]
Thanks for getting back! Well no hurry with that. IMO you and your team are
doing a fantastic job!

**Comment by bennage** [comment]
:-)
