### ISSUE TITLE
Can change the hub-nva.json setting to keep connect via jb-vm1?

### ISSUE THREAD

**Issue by kevinmay** [mspnp/architecture-center#517]
After run the following command:
azbb -s <subscription_id> -g hub-nva-rg -l <location> -p hub-nva.json --deploy

Can't connect to hubjb-vm1, s1jb-vm1 and s1jb-vm2 via jb-vm1. 

Can change the hub-nva.json setting to keep connect via jb-vm1? thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Implementing a hub-spoke network topology in Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?toc=%2fazure%2fvirtual-network%2ftoc.json#deploy-the-solution)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Do you know if you could connect to these VMs before running that step (hub-nva.json)?

**Comment by MikeWasson** [comment]
Update: Looks like this is a bug in the deployment. We're following up.

**Comment by jvannor** [comment]
I'm not sure if this is correct or not, but it seems that the default UDR in hub-gateway-rt broke my site-to-site VPN connections when the RT was applied to the hub-vnet's gateway subnet.  When testing, I removed the default route from this table (0.0.0.0) and replaced it with two more specific routes (10.1.0.0/16 aka spoke1) and (10.2.0.0/16 aka spoke2) and then, the VPN functioned and ping between networks worked.

**Comment by MikeWasson** [comment]
Thanks for reporting this issue. This should be fixed by mspnp/reference-architectures#185
