### ISSUE TITLE
Why write to a store that is never read?

### ISSUE THREAD

**Issue by gunnarsireus** [mspnp/architecture-center#522]
Hello. 
Service A writes to a store which is never read. Or is it read by Service A when needed? Writing data to a store which never is read seems a waste. Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e46426ef-bb0f-b085-a645-7e3e6c05752d
* Version Independent ID: 13b0c53a-cd01-9894-f34f-8d223c8e5b2b
* Content: [CQRS architecture style](https://docs.microsoft.com/en-us/azure/architecture/guide/architecture-styles/cqrs)
* Content Source: [docs/guide/architecture-styles/cqrs.md](https://github.com/mspnp/architecture-center/blob/master/docs/guide/architecture-styles/cqrs.md)
* Service: **guidance**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
In the microservices case, Service A may be reading from the data store, but service B should not read from service A's data store directly.

**Comment by ercananlama** [comment]
I think Service A still needs reading data, for example it might do some validation before processing event request and writing to data store for accuracy. For that, it needs to keep its own data.

**Comment by MikeWasson** [comment]
Yes - I see what you're saying now. The main point of the pattern shown in that section is to separate B's reads, not to say that A shouldn't read from its own data store.
