### ISSUE TITLE
Show each technology on separate page.

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [mspnp/architecture-center#523]
It will be better to split the page in different for each technology in TOC. I've opened "Storage" link and after search was moved to "Cosmos DB" section, which is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Retry service specific guidance](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/retry-service-specific.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Thanks for the suggestion; however most of these sections aren't really long enough to be separate topics, given the way our build/publishing system works.

**Comment by michael-freidgeim-webjet** [comment]
40 minutes to read is above normal single page size.
I also expect that topics should be kept together/separate by relevance, not only by size.
It is unlikely that when a reader opens the page, he/she will be interesting in retry specifics for more than one technology in a time.
