### ISSUE TITLE
Does Exponential RetryPolicy applied if no  DefaultRequestOptions  are specified?

### ISSUE THREAD

**Issue by MNF** [mspnp/architecture-center#525]
The article said:
The following tables show the default settings for the built-in retry policies.
RetryPolicy	Default value ExponentialPolicy.

It is not very clear, does ExponentialPolicy will apply to the client, if no  DefaultRequestOptions  are specified.

Can you add clarification, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Retry service specific guidance](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#azure-storage-retry-guidelines)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/retry-service-specific.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Right, the default retry policy is exponential backoff.
