### ISSUE TITLE
The first picture does not look optimal for dark theme

### ISSUE THREAD

**Issue by slavizh** [mspnp/architecture-center#545]
The first picture does not look optimal for dark theme

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdc23836-c10c-5c47-818b-42c53916b269
* Version Independent ID: b5ef4736-1df9-e3d9-eafb-7782cc0d5fea
* Content: [Best practices for enterprises moving to Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/subscription-governance)
* Content Source: [docs/cloud-adoption-guide/subscription-governance.md](https://github.com/mspnp/architecture-center/blob/master/docs/cloud-adoption-guide/subscription-governance.md)
* Service: **azure-resource-manager**
* Product: **unspecified**
* GitHub Login: @rdendtler
* Microsoft Alias: **rodend;karlku;tomfitz**

**Comment by Petertaylor9999** [comment]
It looks like there's a transparency in the top most element of that graphic. I will fix it.

**Comment by MikeWasson** [comment]
Images look OK now. Note - currently we don't support any kind of image toggling where the dark theme would switch to a different image. White background is the best option.
