### ISSUE TITLE
Error on accessing this page

### ISSUE THREAD

**Issue by rahulupadhyay-capgemini** [mspnp/architecture-center#549]
Hi Microsoft team,

Please find below screenshot which generates a following error. I am highlighting it to so that you can look into the same.

![image](https://user-images.githubusercontent.com/36755260/40673567-bf011804-638f-11e8-8f71-9299851f6d9c.png)
![errormicrosoft](https://user-images.githubusercontent.com/36755260/40673606-dc3f37ca-638f-11e8-8121-d2cac02c26c6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4ecd26-cb7b-4cb2-ae3a-3748ada92771
* Version Independent ID: 97f96179-a22b-8401-a2f4-264a86b5d2f5
* Content: [Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/)
* Content Source: [docs/patterns/index.md](https://github.com/mspnp/architecture-center/blob/master/docs/patterns/index.md)
* Service: **guidance**
* Product: **unspecified**
* GitHub Login: @bennage
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
It seems OK now, maybe it was a transient error?
