### ISSUE TITLE
Enterprise Library Application blocks? really?

### ISSUE THREAD

**Issue by tsahi** [mspnp/architecture-center#551]
You can't seriously recommend using the Transient Fault Handling Application Block or Semantic Logging Application Block. Enterprise Library is officially dead, and no new development is done on it. Specifically with the Transient Fault Handling Application Block, it [notes](https://docs.microsoft.com/en-us/previous-versions/msp-n-p/dn440719(v%3dpandp.60)): "Recent versions of SDKs for both Azure Storage and Azure Service Bus natively support retries. It is recommended to use these instead of the Transient Fault Handling Application Block." Your recommendation on Polly at the end is much more reasonable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Retry service specific guidance](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#general-rest-and-retry-guidelines)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/retry-service-specific.md)
* Service: **guidance**
* Product: **unspecified**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Fair point 😸
