### ISSUE TITLE
The symbols\icons in the icon-set doesn't color-match the Azure Portal.

### ISSUE THREAD

**Issue by Ayanmullick** [mspnp/architecture-center#552]
The Icons in the downloadable icon-set are of a flat color and not the same color as the Azure Portal icons. Also, most of the icons, that belong to resource properties, are missing.  There should be a separate .vss files for each Azure service containing the icons for all  its properties in proper color.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20f420e0-251f-3b3b-75e6-6d6fb1cfd7b7
* Version Independent ID: 1b2c9022-af0b-e6f3-92fc-f3253ebc965d
* Content: [Icons and other assets for architectual diagrams](https://docs.microsoft.com/en-us/azure/architecture/resources/diagrams)
* Content Source: [docs/resources/diagrams.md](https://github.com/mspnp/architecture-center/blob/master/docs/resources/diagrams.md)
* Service: **guidance**
* Product: **unspecified**
* GitHub Login: @bennage
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Hi - Thanks for the feedback. I'll direct this feedback to the team that owns the icons.

**Comment by Ayanmullick** [comment]
https://gallery.technet.microsoft.com/Collection-of-Integration-e6a3f4d0
