### ISSUE TITLE
Add guidance for Data Factory Client

### ISSUE THREAD

**Issue by cmaneu** [mspnp/architecture-center#578]
Azure Data Lake has an official .net Client (`Microsoft.Azure.Management.DataFactory`). 
It would be great to add it to the table.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Retry service specific guidance](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#feedback)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/retry-service-specific.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by hvermis** [comment]
Microsoft.Azure.Management.DataFactory is .Net SDK for Azure Data Factory service, not Azure Data Lake.
Please refer to https://www.nuget.org/packages/Microsoft.Azure.Management.DataFactory/0.8.0-preview and https://azure.microsoft.com/en-us/services/data-factory/ for more information.

**Comment by MikeWasson** [comment]
We recently added a line in the table for Data Lake Store
