### ISSUE TITLE
Add guidance for Data Lake client

### ISSUE THREAD

**Issue by cmaneu** [mspnp/architecture-center#579]
Azure Data Lake has an official .net Client (`Microsoft.Azure.DataLake.Store`). 
It would be great to add it to the table.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Retry service specific guidance](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#feedback)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/retry-service-specific.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by cmaneu** [comment]
By peeking at the source code (https://github.com/Azure/azure-data-lake-store-net/blob/master/AdlsDotNetSDK/ADLSClient.cs#L363), it seems that Retry Policy is built-in into the client SDK. Should I go ahead and submit a PR for adding this?

**Comment by MikeWasson** [comment]
@cmaneu Yes, please go ahead and open a PR and reference this issue.

**Comment by cmaneu** [comment]
@MikeWasson Done :)
