### ISSUE TITLE
SQL underpowered?

### ISSUE THREAD

**Issue by PFCohen** [mspnp/architecture-center#580]
Looking at the server specs; are the SQL boxes underpowered (DSE1_V2) for a farm of this size?  That does not seem like enough cores or memory for a Large HA farm.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d93eb87-54cb-cf38-dfae-0ebe7579d608
* Version Independent ID: c7ac665e-d194-ab07-c1bb-5d5a3049c5ec
* Content: [Run a high availability SharePoint Server 2016 farm in Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/#sharepoint-server-recommendations)
* Content Source: [docs/reference-architectures/sharepoint/index.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/sharepoint/index.md)
* Service: **guidance**
* GitHub Login: @njray
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
The current deployment template actually deploys Standard_DS3_v2 which has 4 cores/8GB RAM.  That should be considered a minimum size. I opened a PR to clarify this in the doc.
