### ISSUE TITLE
Has this ever worked?

### ISSUE THREAD

**Issue by jeffpatton1971** [mspnp/architecture-center#583]
I attempted to follow this, but the examples on the page are incomplete, and the linked repo did not contain this method of deployment, at least in any form I could discern. I've attempted to duplicate what I see in this document but it's failing, additionally it appears that there are either errors, or omissions. Can we either get the templates re-written in a working fashion, or a link to where these can be found online? 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb5b79f5-7069-cc1c-819d-81e1aa90a498
* Version Independent ID: df9cebf2-43d3-869a-d591-aedfe75f59f4
* Content: [Implement a property transformer and collector in an Azure Resource Manager template](https://docs.microsoft.com/en-us/azure/architecture/building-blocks/extending-templates/collector)
* Content Source: [docs/building-blocks/extending-templates/collector.md](https://github.com/mspnp/architecture-center/blob/master/docs/building-blocks/extending-templates/collector.md)
* Service: **guidance**
* GitHub Login: @petertay
* Microsoft Alias: **pnp**

**Comment by jeffpatton1971** [comment]
So, I got bored last night and got this working, I had some issues with the deployment() function so i skipped out of it, as there is potentially either a bug in visual studio around deployment() or an issue with the documentation.

https://github.com/jeffpatton1971/arm-property-transform-collector/tree/v1.1

This is a working version of the code on the transformer collector doc, as written.

**Comment by pckls** [comment]
I had commented a working version of this but it was before they switched over to using GitHub :)

https://github.com/pckls/azure-resource-manager-templates/tree/master/property-transformer-and-collector
