### ISSUE TITLE
Add comparison points to Stream Processing tech choices

### ISSUE THREAD

**Issue by MikeWasson** [mspnp/architecture-center#611]
Suggestion from @mamccrea

In [Choosing a stream processing technology in Azure](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/stream-processing), add comparison points for:

- Geospatial support
- Substream support (e.g., TIMESTAMP BY ... OVER in Stream Analytics)

**Comment by MikeWasson** [comment]
Both of these patterns can be done in Spark, tho' not necessarily using built-in features of the spark engine.

**Comment by mamccrea** [comment]
@MikeWasson - are we able to add the patterns to the table with ASA and Spark both supporting them?
