### ISSUE TITLE
Possible typo: should "sqlVersion: "sql2014ee" be "sqlVersion" : "sql2014ee"?

### ISSUE THREAD

**Issue by jwatkin** [mspnp/architecture-center#616]
On this page:
[https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions)

In the "Organize resources with tags" section, there's an example tag written as: "sqlVersion: "sql2014ee", with unbalanced quotes. However, in earlier examples it's suggested to use this format -> "sqlVersion" : "sql2014ee". Is this a typo?

Also, the Feedback mechanism on that page appears to be broken. I got an error when I tried to submit my comment directly from that page. I had to go directly into GitHub to submit this comment.

**Comment by MikeWasson** [comment]
Thanks. Yes, I think the intent is to show the key + value. I'll fix this. Note the actual syntax for [setting tags](https://docs.microsoft.com/azure/azure-resource-manager/resource-group-using-tags) depends on whether you're using PowerShell, CLI, or Portal.
