### ISSUE TITLE
Should Azure Container Instances really be recommended?

### ISSUE THREAD

**Issue by algattik** [mspnp/architecture-center#635]
The doc states "Use the Azure Container Agents plugin to run a container as an agent in either Azure Container Service with Kubernetes, or Azure Container Instances.", but the Jenkins plugin page https://plugins.jenkins.io/azure-container-agents says of the ACI connector "this software is experimental and should not be used for anything resembling a production workload."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44c5ba03-a6ce-5d5c-fb83-e3e4e13da80d
* Version Independent ID: 6f235fae-19ab-9b12-72a9-f9962076ef5b
* Content: [Run a Jenkins server on Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/jenkins/index)
* Content Source: [docs/reference-architectures/jenkins/index.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/jenkins/index.md)
* Service: **guidance**
* GitHub Login: @njray
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
You shouldn't need to use aci-connector-k8s for ACI. See the section "Azure Container Instance" in the plugin page.
