### ISSUE TITLE
Service Fabric for Long running jobs

### ISSUE THREAD

**Issue by vinomanoharan** [mspnp/architecture-center#679]
Hi 

Whether service fabric considered for long running jobs?

Thanks
Vino

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50a65e47-b024-0c7c-0ee9-21ff095abafd
* Version Independent ID: a764689a-168d-dcef-a297-c47f84ea2d12
* Content: [Background jobs guidance](https://docs.microsoft.com/en-us/azure/architecture/best-practices/background-jobs)
* Content Source: [docs/best-practices/background-jobs.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/background-jobs.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by vinomanoharan** [comment]
This help document is not updated for sometime. Can you updated with other azure options for long running jobs.

**Comment by dragon119** [comment]
@vinomanoharan  Thank you for your comment. Technically speaking, we can use anything for long running jobs but we're focusing on most popular options among our customers here.

**Comment by SychevIgor** [comment]
Totally agree with @vinomanoharan , guide requires some actualization to address latest trends in Microsoft Azure. For example AKS instead of ACS. https://github.com/mspnp/architecture-center/issues/885
Otherwise it looks like - either guides are too conservative, or simple out-of-date.
