### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by pappasa** [mspnp/architecture-center#680]
Are transactions possible across several Microservices?

**Comment by MikeWasson** [comment]
Yes, but generally not with a single atomic transaction. Instead you would execute a sequence of local transactions. You need a way to coordinate across the services, using something like [Scheduler Agent Supervisor pattern](https://docs.microsoft.com/azure/architecture/patterns/scheduler-agent-supervisor). You also need to be able to apply a [compensating transaction](https://docs.microsoft.com/azure/architecture/patterns/compensating-transaction) in case something goes wrong. 

Our Microservices design guide goes into this, in the section on [workflows](https://docs.microsoft.com/en-us/azure/architecture/microservices/ingestion-workflow#workflow).

**Comment by MikeWasson** [comment]
Here's another good resource on this topic: https://blog.couchbase.com/saga-pattern-implement-business-transactions-using-microservices-part/
