### ISSUE TITLE
Feedback to add a point in section "General Considerations > Functional requirements" as "Region or Location of data."

### ISSUE THREAD

**Issue by jpchauhan** [mspnp/architecture-center#681]
Hi,

In "General Considerations > Functional requirements" section, is it make sense to add one more point as stated below?

Region or Location of data. What is a Region? Where are the regions located? What are the different capabilities of the regions with respect to each other?
What are the preview features vs. general availability within a region? Are there any restrictions on where you can deploy to a region? For example: Legal compliance, Government regulations?

For more information please refer: http://mscloud.be/azure-locations-regions-datacenters-fault-domains-update-domains-clusters-availability-sets/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40cb85c-ee53-7b49-0622-bed8ebedea81
* Version Independent ID: 896e0838-dfd1-c442-414d-ad9ea6dc8f7d
* Content: [Criteria for choosing a data store](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-comparison#shared-files)
* Content Source: [docs/guide/technology-choices/data-store-comparison.md](https://github.com/mspnp/architecture-center/blob/master/docs/guide/technology-choices/data-store-comparison.md)
* Service: **guidance**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by dragon119** [comment]
@jpchauhan Thank you for your feedback. This guidance is high level comparison among different storage types so the question about Azure service availability in a particular region is not relevant here. However that's a good question when you choose Azure services. We'll include this discussion when we work on Azure specific storage guidance.
