### ISSUE TITLE
Should the client retry for the 408 response code 

### ISSUE THREAD

**Issue by bingosummer** [mspnp/architecture-center#682]
The response code 408 means a Request Timeout error. In the [General REST and retry guidelines](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#general-rest-and-retry-guidelines), 408 is a retrable error.
Should [Azure Active Directory retry guidelines](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#azure-active-directory) retry for 408?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Retry service specific guidance](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#azure-active-directory)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/retry-service-specific.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by dragon119** [comment]
@bingosummer Thank you for your feedback. Since we don't have a "client library" for general REST, we share the list of errors that you should retry. For AAD in particular, we recommend to use Active Directory Authentication Library (ADAL) to handle transient faults.
