### ISSUE TITLE
Resources outside Hub/Spoke topology

### ISSUE THREAD

**Issue by prara06** [mspnp/architecture-center#694]
My client has setup Express Route from on prem to Azure with Hub and Spoke topology. (central region)
Need to provision few resources that are available only in EAST US.  (temporary 3 months)

1. What should be my strategy to extend hub/spoke to the new region EAST US so that users can access the resource from ON prem network. 
2. Can Hub/Spoke topology span across multiple regions? Else what options do I got.
Please advice.

**Comment by atoakley** [comment]
The Hub and Spoke reference architecture uses VNet Peering between the hub and spokes.  Global VNet Peering is generally available, so you should be able to peer your East US region Vnet with your Central region Hub VNet.  Go [here](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-peering-overview) for more information.
