### ISSUE TITLE
Broken link in "Azure governance design guide" topic

### ISSUE THREAD

**Issue by MikeWasson** [mspnp/architecture-center#703]
In this doc, the link to "Microsoft Enterprise Agreement" is broken:

https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption-guide/adoption-intro/governance-how-to

**Comment by MikeWasson** [comment]
related to #700

**Comment by Petertaylor9999** [comment]
This is really confusing. There was a new link in the other PR, and it was the correct one. I'll open a new PR to fix it.

**Comment by Petertaylor9999** [comment]
Sorry - I see now what they did. I'll fix it.
