### ISSUE TITLE
Nice article! 

### ISSUE THREAD

**Issue by jpchauhan** [mspnp/architecture-center#706]
Nice article! 
It helped to understand various things in a systemic and structured way. Keep it up!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c337b22b-b387-5eea-9b16-656885eae759
* Version Independent ID: 6c1ad9b6-fdf4-f23a-20dc-118f262d0a8c
* Content: [Automated enterprise BI with SQL Data Warehouse and Azure Data Factory](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/enterprise-bi-adf)
* Content Source: [docs/reference-architectures/data/enterprise-bi-adf.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/data/enterprise-bi-adf.md)
* Service: **guidance**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
thanks!
