### ISSUE TITLE
Nice article! 

### ISSUE THREAD

**Issue by jpchauhan** [mspnp/architecture-center#707]
Nice article! 
It helped to understand various things in a systemic and structured way. Keep it up!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2581991e-753b-4512-b5cf-aab7bb5e28f5
* Version Independent ID: 065e2d61-5a0d-4581-533b-2d9dd4de8aae
* Content: [Enterprise BI with SQL Data Warehouse](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/enterprise-bi-sqldw#next-steps)
* Content Source: [docs/reference-architectures/data/enterprise-bi-sqldw.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/data/enterprise-bi-sqldw.md)
* Service: **guidance**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
thanks!
