### ISSUE TITLE
Microservices / container orchestrators	 title mismatch

### ISSUE THREAD

**Issue by imran30758** [mspnp/architecture-center#713]
In Compute category "Microservices / container orchestrators" , the AWS service is "Elastic Container Service for Kubernetes (EKS)" and the equivalent service of Azure should be "Azure Kubernetes Service (AKS)" while it suggests "Azure Container Service (AKS)". I believe the title should be looked at. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [Azure and AWS services compared - multicloud](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/mspnp/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **guidance**
* GitHub Login: @lbrader
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
@imran30758 Yes, thanks. The name changed when the service went GA.
