### ISSUE TITLE
Mixed IaaS and PaaS architectures

### ISSUE THREAD

**Issue by MartinDiewald** [mspnp/architecture-center#714]
Could you also provide an n-tier architecture if
1. WebTier runs on WebApp
2. WebTier runs on AKS
3. DB Tier runs on SQL Service
That would help a lot.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e5ad897-88ad-5298-b9ff-4d988af52466
* Version Independent ID: 8a3904d9-17ed-0ac0-f006-6997095c86bb
* Content: [N-tier architecture style](https://docs.microsoft.com/en-us/azure/architecture/guide/architecture-styles/n-tier)
* Content Source: [docs/guide/architecture-styles/n-tier.md](https://github.com/mspnp/architecture-center/blob/master/docs/guide/architecture-styles/n-tier.md)
* Service: **guidance**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
1. [This article](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/basic-web-app) shows an N-tier App Service application (where N=2). You could add a business layer in the web app.

2. An AKS reference architecture is on our backlog. Also our [microservices guide](https://docs.microsoft.com/en-us/azure/architecture/microservices/) uses the older ACS service, but the concepts are very similar

3. Do you mean a mixed IaaS + Azure SQL Database deployment? We use [Azure Building Blocks](https://github.com/mspnp/template-building-blocks/wiki) in the n-tier reference architecture. Building Blocks doesn't support Azure SQL Database, so you'd need a separate Resource Manager template to deploy it. Also consider using [managed identities](https://docs.microtsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview) to authenticate with SQL Database.
