### ISSUE TITLE
Linked Visio file does not match the displayed architecture diagram

### ISSUE THREAD

**Issue by scarson** [mspnp/architecture-center#720]
Currently links to https://archcenter.blob.core.windows.net/cdn/hybrid-network-hub-spoke.vsdx which appears to be an older, out of date version.

Compare to the current image: https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/images/shared-services.png 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87139748-938e-638e-de1f-94f8becfe1da
* Version Independent ID: b96371e6-defb-3e70-792a-2c0cfdc25b7d
* Content: [Implementing a hub-spoke network topology with shared services in Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/shared-services)
* Content Source: [docs/reference-architectures/hybrid-networking/shared-services.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/shared-services.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Uploaded correct version of the Visio

**Comment by Trey432** [comment]
I'm still not seeing the correct Visio diagram when using the download link.

**Comment by MikeWasson** [comment]
@Trey432 - Are you looking at the "Shared Services" tab on the Visio? The file has two diagrams, hub-spoke and hub-spoke with shared services. (I just downloaded it and they look the same to me unless I'm missing something 😺 )

**Comment by Trey432** [comment]
Yeah, my mistake.  I didn't realize that there was another tab.  Thanks for the quick response!
