### ISSUE TITLE
Linked Visio file does not match the displayed architecture diagram

### ISSUE THREAD

**Issue by scarson** [mspnp/architecture-center#721]
Currently links to https://archcenter.blob.core.windows.net/cdn/hybrid-network-hub-spoke.vsdx which appears to be an older, out of date version.

Compare to the current image: https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/images/hub-spoke.png

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Implementing a hub-spoke network topology in Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Stupidly I can't find the updated Visio, so I may have to recreate it. :frowning:

**Comment by MikeWasson** [comment]
Uploaded correct version of the Visio
