### ISSUE TITLE
apache flink

### ISSUE THREAD

**Issue by javias** [mspnp/architecture-center#725]
does Azure support Apache Flink as a streaming platform with event hub?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 957618b3-8d25-49c4-950c-0c044d68f443
* Version Independent ID: 2ab67665-066b-fb14-9763-a12693b19bec
* Content: [Choosing a stream processing technology](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/stream-processing)
* Content Source: [docs/data-guide/technology-choices/stream-processing.md](https://github.com/mspnp/architecture-center/blob/master/docs/data-guide/technology-choices/stream-processing.md)
* Service: **guidance**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
@javias Please see this doc: [Use Apache Flink with Azure Event Hubs for Apache Kafka](https://docs.microsoft.com/azure/event-hubs/event-hubs-kafka-flink-tutorial)
