### ISSUE TITLE
Stream Analytics job output to CosmosDB graph

### ISSUE THREAD

**Issue by PedroRiveraTorresMoir** [mspnp/architecture-center#733]
Is saving the output of a Stream Analytics job as a graph in CosmosDB with the Gremlin API in the roadmap? This would improve the data architecture of the whole flow significantly. Especially query times. Graph is the right database for most of these use cases anyways, IMO -- especially when you imagine visualizing not just real time data in PowerBI, but also the wealth of historical data that was saved.

Thanks for any information you might share on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dbabb84-7f78-9959-ab50-d25da52df642
* Version Independent ID: b827dce6-e4be-40f6-bf52-7f8e30dfcf2e
* Content: [Stream processing with Azure Stream Analytics](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/data/stream-processing-stream-analytics)
* Content Source: [docs/reference-architectures/data/stream-processing-stream-analytics.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/data/stream-processing-stream-analytics.md)
* Service: **guidance**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hello @PedroRiveraTorresMoir 

Thank you for your feedback, and apologies for delay in response! Were you able to locate an answer to your question via different means and make further progress? Please let us know, otherwise, we'll proceed to close this issue.

**Comment by MikeWasson** [comment]
@PedroRiveraTorresMoir  Hi - Updating this particular reference architecture to use Gremlin API isn't on our current roadmap, but I agree that guidance about graph databases would be useful. We can add that to our backlog, tho' I can't guarantee when we'd get to it.

**Comment by PedroRiveraTorresMoir** [comment]
Thanks, I'd appreciate it. I find it odd that Cosmos DB was developed with graph capabilities in mind, and that Microsoft is investing so heavily in IoT, and yet there's no way to send data from Azure IoT Hub to Cosmos DB Graph. Very bizarre that it's not in the roadmap IMO, as IoT is probably the best use case for graph databases, right along with social networks.

**Comment by MikeWasson** [comment]
I've added this to our internal backlog.

**Comment by MikeWasson** [comment]
@PedroRiveraTorresMoir  As a follow-up, we have a User Voice now for architectural guidance. We added an item for [graph database guidance](https://azure-architecture.uservoice.com/forums/918628-cloud-fundamentals/suggestions/36682087-i-d-like-to-learn-more-about-how-graph-databases-w).
