### ISSUE TITLE
Service Bus Retry Mechanism

### ISSUE THREAD

**Issue by mloho** [mspnp/architecture-center#752]
How is Service Bus' built-in retry mechanism supposed to work in tandem with my own retry mechanism?
This question makes some sense when we take a look at a simple scenario from the SB library caller's point of view:

1. receive a message
2. complete the message
3. the complete call throws a transient Service Bus exception (for example: TimeoutException)
4. handle the exception: determine its `isTransient()` return value
    1. if the exception is not transient, then deadletter the message
    2. if the exception is transient, then re-call the complete method at a later time (to be specific, currently I am doing 5 seconds, then 10, 15, 20, and then deadletter altogether)

First of all, do the above "exception handling" steps make sense to do? Did the built-in SB retry mechanism even run? If it did run (or not) and I get a transient exception then what does this mean? Am I supposed to continue the retry logic and retry the operation myself or just abandon the message or what?

Also, the [Service Bus messaging exceptions page](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-exceptions) states whether to retry or not for a set of Service Bus exceptions, yet it fails to mention [this page](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#service-bus) which describes the existence of this built-in retry mechanism. Please make both pages reference each other. Unless they are totally unrelated which could explain my current confusion and the existence of this ticket.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Retry service specific guidance](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#service-bus)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/retry-service-specific.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
The RetryPolicy class handles the retry logic by looking at IsTransient. The steps you list are basically what the RetryPolicy class does - See [here](https://github.com/Azure/azure-service-bus-dotnet/blob/master/src/Microsoft.Azure.ServiceBus/RetryPolicy.cs#L142). 

From the doc:

> The built-in RetryExponential policy relies on the IsTransient property

I agree the page on SB exceptions should mention RetryPolicy
