### ISSUE TITLE
This article requires monthly or at least quarterly update

### ISSUE THREAD

**Issue by mvark** [mspnp/architecture-center#764]
This is a very useful comparison table. Please keep updating it regularly to show the new  services that are added, remove the Preview suffix for services which are now generally available 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [Azure and AWS services compared - multicloud](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/mspnp/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **guidance**
* GitHub Login: @lbrader
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Thanks - we try to keep it updated 😺 
I've removed the "preview" label for Standard DDoS and WAF which are both GA
