### ISSUE TITLE
spokes to spokes connection without NVA

### ISSUE THREAD

**Issue by jackchenquest** [mspnp/architecture-center#765]
I wasn't ware the NVA option when I setup onprem to hub to spokes network, but I found a workaround to make sopkes to spokes connection work. I think it's much easier and simpler to setup. the trick is just add a bigger address space into the S2S VPN's local network gateway.

Lets say the onprem network has address 10.0.0.0/16,   hub vnet has address 10.1.0.0/24, I can configure spoke vnet has address 10.1.32.0/24, 10.1.33.0/24, 10.1.34.0/24, etc.  then I can add 10.1.32.0/19 into local network gateway as VPN remote address. This will trigger hub gateway to advertise 10.1.32.0/19 to all the spokes network. and it seems doesn't cause any problem, since hub and spokes network has more accurate route for individual 10.1.xx.0/24 subnet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Implementing a hub-spoke network topology in Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Thank you for sharing, @jackchenquest!

We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
