### ISSUE TITLE
aws-professional: Two Minor issues

### ISSUE THREAD

**Issue by andreas-wilm** [mspnp/architecture-center#788]
Hello there, I found two minor issue with aws-professional/index.md:

1.  it refers twice to the "Complete AWS and Azure service comparison matrix" twice, but the target is simply the british-english version of this same webpage.

2. it states that ""Azure has no equivalent to EC2 Spot Instances", but what about Low-Priority VM?

Thanks, Andreas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d100d43f-d48a-3d97-1aea-7a5409fdccc8
* Version Independent ID: 568dcd88-b93c-1d41-44d0-8643dd057a33
* Content: [Azure for AWS Professionals](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/)
* Content Source: [docs/aws-professional/index.md](https://github.com/mspnp/architecture-center/blob/master/docs/aws-professional/index.md)
* Service: **guidance**
* GitHub Login: @lbrader
* Microsoft Alias: **pnp**

**Comment by eyusubov** [comment]
I am not able to find "Azure has no equivalent to EC2 Spot Instances".
Actually there a Azure spot instances now.
