### ISSUE TITLE
Few ideas for the poster/infographic

### ISSUE THREAD

**Issue by lookfwd** [mspnp/architecture-center#795]
Looking at the poster from [here](https://docs.microsoft.com/en-us/previous-versions/msp-n-p/dn568099(v=pandp.10)), some details: 1) on the CQRS-pattern were you say "Date persistence", you likely meant "Data persistence", 2) it would be nice to have this in white background so it's easier to print, 3) Port 80 should be HTTP on Health Endpoint Monitoring, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5834892d-cf50-ccc8-8f6e-b1352874a146
* Version Independent ID: e10b0743-6d33-3c00-d81a-077e9f43c793
* Content: [Designing, building, and operating microservices on Azure with Kubernetes](https://docs.microsoft.com/en-us/azure/architecture/microservices/)
* Content Source: [docs/microservices/index.md](https://github.com/mspnp/architecture-center/blob/master/docs/microservices/index.md)
* Service: **guidance**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Hi - Thank for pointing these out. I'm not sure we have any plans to update this poster but I've captured this feedback in our backlog
