### ISSUE TITLE
Uniqueness of Azure AD Security Group object id

### ISSUE THREAD

**Issue by juho-hanhimaki** [mspnp/architecture-center#824]
Is the object id of Azure AD Security Group guaranteed to be globally unique across the whole Azure AD (all tenants)?

This is key information for actually implementing the "Roles using Azure AD security groups" scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184d69e-7219-f4f0-6583-32f79f5a76e1
* Version Independent ID: 49e5b0f0-69cb-4ab1-c8d9-62eb07778a88
* Content: [Application roles](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/app-roles#roles-using-azure-ad-security-groups)
* Content Source: [docs/multitenant-identity/app-roles.md](https://github.com/mspnp/architecture-center/blob/master/docs/multitenant-identity/app-roles.md)
* Service: **guidance**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Per [this doc](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-id-and-access-tokens), the ID is unique (it's a UUID)
