### ISSUE TITLE
Removal of peering restrictions

### ISSUE THREAD

**Issue by DazzleJim** [mspnp/architecture-center#828]
Referring to section "Recommendations - Resource Groups" - Update to text needed as regional limitations and Azure AD tenant restrictions no longer apply when peering.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Implementing a hub-spoke network topology in Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?toc=/azure/virtual-network/toc.json)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Yes, that's a good point - thanks!
