### ISSUE TITLE
Service mismatch for Lambda@Edge

### ISSUE THREAD

**Issue by julianpitt** [mspnp/architecture-center#831]
The comparison service is listed as Functions on Azure IoT Edge which would be better suited to AWS Greengrass.
Lambda @ Edge allows you to run lambda functions at the CDN edge location reducing latency.
To my (limited Azure) knowledge, there isn't a corresponding Azure solution for running functions at a CDN edge location.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [Azure and AWS services compared - multicloud](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/mspnp/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **guidance**
* GitHub Login: @lbrader
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Good catch, thanks. I'll remove that entry from the table.
