### ISSUE TITLE
Support Edge reading mode

### ISSUE THREAD

**Issue by VijayManchi** [mspnp/architecture-center#834]
It would great if docs.microsoft.com articles supports Microsoft edge reading mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 050bb1fd-56ca-63bc-b105-17a56e3b0362
* Version Independent ID: ce84d0a7-3596-e259-dfc3-a9789efd9948
* Content: [Sharding](https://docs.microsoft.com/en-us/azure/architecture/patterns/sharding#feedback)
* Content Source: [docs/patterns/sharding.md](https://github.com/mspnp/architecture-center/blob/master/docs/patterns/sharding.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Thanks for the feedback - Can I ask you to open this issue in the [https://github.com/MicrosoftDocs/feedback](https://github.com/MicrosoftDocs/feedback) repo?
