### ISSUE TITLE
ASP.NET Web API 2, Owin, OAuth, Bearer Token, Refresh Token with custom database

### ISSUE THREAD

**Issue by AliAdravi** [mspnp/architecture-center#839]
This article is good for those who want to use the bearer token without refresh token.
If you want to implement refresh token see the following article for detail:

http://www.advancesharp.com/blog/1236/asp-net-web-api-2-owin-oauth-bearer-token-refresh-token-with-custom-database

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31e618c7-7784-f35b-ed8b-180c2b2b9994
* Version Independent ID: 318854a1-21ef-436a-e142-ee2dae535a22
* Content: [Secure a backend web API in a multitenant application](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/web-api)
* Content Source: [docs/multitenant-identity/web-api.md](https://github.com/mspnp/architecture-center/blob/master/docs/multitenant-identity/web-api.md)
* Service: **guidance**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Thanks for sharing, @AliAdravi!

We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
