### ISSUE TITLE
update the diagram

### ISSUE THREAD

**Issue by knssub** [mspnp/architecture-center#844]
[Enter feedback here]

Wondering if with the recent integration of various services into Azure Monitor, the diagram would need an update? If not, could you please clarify if we still need to keep all 3 components (App insights, Monitor and Log Analytics). https://azure.microsoft.com/en-us/blog/new-full-stack-monitoring-capabilities-in-azure-monitor/
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df354e21-f263-30a9-1a5c-1460f2bf16a9
* Version Independent ID: 73d2f19b-00a0-fe4d-7042-15d27f586565
* Content: [Web application monitoring on Azure](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/app-monitoring)
* Content Source: [docs/example-scenario/apps/app-monitoring.md](https://github.com/mspnp/architecture-center/blob/master/docs/example-scenario/apps/app-monitoring.md)
* Service: **guidance**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
I think the diagram is still accurate in terms of showing the data flow.
