### ISSUE TITLE
Contributing to translated versions

### ISSUE THREAD

**Issue by OtacilioN** [mspnp/architecture-center#845]
Hey Folks,

I would like to contribute with the Portuguese from Brazil translated versions and I am not finding here how to do this. Would be great to do this since the Brazilian versions are readable but still can be improved (In the translation aspect).

So what do you think to add this flow in the [CONTRIBUTING.md](https://github.com/mspnp/architecture-center/blob/master/CONTRIBUTING.md) guide? Or even maybe adding this flow at [contributing-to](https://github.com/mspnp/architecture-center/tree/master/contributing-to) folder.

Cheers,
Otacilio Maia.

**Comment by OtacilioN** [comment]
Hey sorry, now I saw a button called "edit" in the top of the Portuguese from Brazil version, and it is awesome! I will still maintain this issue opened to discuss about adding a file called "contribute-to"

**Comment by mike-urnun-msft** [comment]
Hello @OtacilioN 

Thanks for the KUDOS, and apologies for delay in response. It sounds like you were able locate the right process for driving contribution towards this content -- GREAT!

As such, we will now proceed to close this thread for now. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
