### ISSUE TITLE
Naming rules and restrictions for Resource Group Name

### ISSUE THREAD

**Issue by KeiroKamioka0000** [mspnp/architecture-center#848]
According the document says, it support the Unicode Text.
However, such as ①、Some of Unicode Strings cannot be used.

May I ask for more specific detail?
 
https://www.fileformat.info/info/unicode/char/2460/index.htm

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Naming conventions for Azure resources](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/naming-conventions.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Fixed by #865
