### ISSUE TITLE
VM scale set vs. Availability set.

### ISSUE THREAD

**Issue by spmanjunath** [mspnp/architecture-center#850]
Is it right to say the "VM Scale set" is an alternative to "Availability set"?  They serve two distinct purposes, perhaps the below sentence requires rephrasing,
"VM scale set (not shown). A VM scale set is an alternative to using an availability set. A scale sets makes it easy to scale out the VMs in a tier, either manually or automatically based on predefined rules."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142dd377-b9db-b526-d4f2-51310cf6a926
* Version Independent ID: 954769a7-e6cf-ed89-e9cc-5c2e63f9890e
* Content: [N-tier application with SQL Server](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/n-tier/n-tier-sql-server?toc=%2Fazure%2Fvirtual-machines%2Fwindows%2Ftoc.json)
* Content Source: [docs/reference-architectures/n-tier/n-tier-sql-server.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/n-tier/n-tier-sql-server.md)
* Service: **guidance**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Thanks for the feedback. Technically you can't place a scale set in an availability set, so it's an alternative in that sense. But I agree, scale sets solve a different problem, so the doc could be clearer.
