### ISSUE TITLE
Images does not changes when "Read in english" is selected from a translated version.

### ISSUE THREAD

**Issue by OtacilioN** [mspnp/architecture-center#854]
When you are in a translated version of a document, such as in https://docs.microsoft.com/pt-br/azure/architecture/patterns/pipes-and-filters, you have a slider called "Read in English", when you active the slider all the text is translated, but the images stills the same, with texts in the original language (Portuguese in the case)

**Comment by MikeWasson** [comment]
Hi - Since that's a feature of our publishing platform, can I ask you to open the issue at this repo?

https://github.com/MicrosoftDocs/feedback/issues

Thanks!

**Comment by OtacilioN** [comment]
Okay, thanks @mikewarr, opening there!
