### ISSUE TITLE
Exchange Online

### ISSUE THREAD

**Issue by aldoug** [mspnp/architecture-center#861]
I think this could be used to reflect similar conversations with the above. Perhaps some conversations with EXO Transport Engineering to see if could be the case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53ff3ea0-9b53-16bb-b81f-a12074ad75d0
* Version Independent ID: 4e37c8ba-cbb5-1e3d-6186-ccb2ed6553bd
* Content: [Retry general guidance](https://docs.microsoft.com/en-us/azure/architecture/best-practices/transient-faults)
* Content Source: [docs/best-practices/transient-faults.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/transient-faults.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Sorry, I don't understand the context here. Did you mean to open the issue in this repo?
