### ISSUE TITLE
Which tool is used to draw the diagram in this article,Thanks!

### ISSUE THREAD

**Issue by CwjXFH** [mspnp/architecture-center#869]
Which tool is used to draw the diagram in this [article](https://docs.microsoft.com/en-us/azure/architecture/patterns/cqrs),Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43af0b36-1389-2302-9c67-5e6560c9814b
* Version Independent ID: 235ef144-78ca-1fbc-e3f8-e69afcc04ff5
* Content: [CQRS](https://docs.microsoft.com/en-us/azure/architecture/patterns/cqrs)
* Content Source: [docs/patterns/cqrs.md](https://github.com/mspnp/architecture-center/blob/master/docs/patterns/cqrs.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Those were actually created a long time ago, but I'm guessing it was Visio.
