### ISSUE TITLE
Confused about partitioning strategy for blobs...

### ISSUE THREAD

**Issue by NelsonLamprecht** [mspnp/architecture-center#877]
This current page says "The partition key for a blob is account name + container name + blob name" where as this page "https://docs.microsoft.com/en-us/azure/storage/common/storage-performance-checklist?toc=%2fazure%2fstorage%2fblobs%2ftoc.json#subheading47" says we should prefix the various parts so the load balancing operations can be effective... (http://sigops.org/s/conferences/sosp/2011/current/2011-Cascais/printable/11-calder.pdf)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51bec992-bf19-01e4-107d-d70a83febceb
* Version Independent ID: 072c2533-b725-26a6-f294-82f825cd0fbd
* Content: [Data partitioning guidance](https://docs.microsoft.com/en-us/azure/architecture/best-practices/data-partitioning#partitioning-azure-blob-storage)
* Content Source: [docs/best-practices/data-partitioning.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/data-partitioning.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by dragon119** [comment]
@NelsonLamprecht , thank you for your feedback. I agree. We'll add a reference to the article you suggested.
