### ISSUE TITLE
Wrong full form of RBAC

### ISSUE THREAD

**Issue by githubavi** [mspnp/architecture-center#881]
In this document RBAC has been mentioned as resource based access control (RBAC). It should be Role Based Access Control

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31205281-634d-58aa-d6f5-832502786a49
* Version Independent ID: aa764653-fc4d-0afe-b5da-b7773f3c35b9
* Content: [Enterprise Cloud Adoption: What is cloud resource governance?](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/getting-started/what-is-governance)
* Content Source: [docs/cloud-adoption/getting-started/what-is-governance.md](https://github.com/mspnp/architecture-center/blob/master/docs/cloud-adoption/getting-started/what-is-governance.md)
* Service: **guidance**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hello @githubavi 

Thank you for reporting this issue! We will review and make any necessary changes.
