### ISSUE TITLE
AKS instead or with ACS

### ISSUE THREAD

**Issue by SychevIgor** [mspnp/architecture-center#885]
As of today, AKS is a recommended managed container service in Azure. It will be nice to mention it a
https://docs.microsoft.com/en-us/azure/architecture/best-practices/background-jobs#hosting-environment  section
Agree, ACS not yet decommissioned, but it will be right to follow latest Azure releases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50a65e47-b024-0c7c-0ee9-21ff095abafd
* Version Independent ID: a764689a-168d-dcef-a297-c47f84ea2d12
* Content: [Background jobs guidance](https://docs.microsoft.com/en-us/azure/architecture/best-practices/background-jobs#hosting-environment)
* Content Source: [docs/best-practices/background-jobs.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/background-jobs.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by dragon119** [comment]
@SychevIgor , thank you for your feedback. We'll make the change you suggested.
