### ISSUE TITLE
Azure DevOps instead of VSTS

### ISSUE THREAD

**Issue by SychevIgor** [mspnp/architecture-center#888]
Will be nice to update this diagram to follow latest branding https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/media/architecture-devops-dotnet-webapp.png
Azure DevOps instead of VSTS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8865190-b9ac-ae5e-2590-30237ed43697
* Version Independent ID: 45d8bb8c-10f1-de72-6644-a20ba60a32af
* Content: [CI/CD pipeline with Azure DevOps](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/devops-dotnet-webapp)
* Content Source: [docs/example-scenario/apps/devops-dotnet-webapp.md](https://github.com/mspnp/architecture-center/blob/master/docs/example-scenario/apps/devops-dotnet-webapp.md)
* Service: **guidance**
* GitHub Login: @christianreddington
* Microsoft Alias: **pnp**

**Comment by adamboeglin** [comment]
This has been fixed.
