### ISSUE TITLE
PDF download link needs to be updated

### ISSUE THREAD

**Issue by prad-man** [mspnp/architecture-center#890]
The PDF link does not include some updates (Databox missing in downloadable PDF for instance). You may want to point it to the latest version for download.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [Azure and AWS services compared - multicloud](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/mspnp/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **guidance**
* GitHub Login: @lbrader
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Yes, thanks -- That PDF is definitely outdated, but we don't have plans to update it. I'll remove the link.
