### ISSUE TITLE
Redis Cache example

### ISSUE THREAD

**Issue by SychevIgor** [mspnp/architecture-center#897]
I think, first of all we must mention that it's StackExchange.Redis implementation. From this article- it's not clear. As well as mention, that it's one of possible implementation for .net, because our friends from Pluralsight creating question for "architecture" roleIQ based on this documentation and asking about this client as about only single possible implementation. 

Second moment, I would suggest to rephrase this "The GetMyEntityAsync method in the following code example shows an implementation of the Cache-Aside pattern based on Azure Redis Cache", because code is Redis specific, not Azure Redis Cache specific. For a not expert in a question, this sentence could tell that Redis in Azure significantly different from regular Redis implementation 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67f58625-4e97-1fc6-197b-8b25341f5a4f
* Version Independent ID: bdabf990-9a18-ec7f-a948-3fc79dc255e0
* Content: [Cache-Aside](https://docs.microsoft.com/en-us/azure/architecture/patterns/cache-aside)
* Content Source: [docs/patterns/cache-aside.md](https://github.com/mspnp/architecture-center/blob/master/docs/patterns/cache-aside.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Good point - I'll clarify this in the doc.
