### ISSUE TITLE
Azure Application Gateway link

### ISSUE THREAD

**Issue by SychevIgor** [mspnp/architecture-center#898]
If in an article will be a link to an Azure Application Gateway as an example of this pattern implementation in Azure Service- it will be useful https://docs.microsoft.com/en-us/azure/application-gateway/overview#url-based-routing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c4012e4-f0a1-ee9d-781f-cea7e5aca94d
* Version Independent ID: 259d4085-3a00-44f6-f82c-f5cbfe633689
* Content: [Gateway Routing pattern](https://docs.microsoft.com/en-us/azure/architecture/patterns/gateway-routing)
* Content Source: [docs/patterns/gateway-routing.md](https://github.com/mspnp/architecture-center/blob/master/docs/patterns/gateway-routing.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hello @SychevIgor 

Thank you for valuable feedback! We will review and make any necessary changes.
