### ISSUE TITLE
Azure Application Gateway link

### ISSUE THREAD

**Issue by SychevIgor** [mspnp/architecture-center#899]
If in an article will be a link to an Azure Application Gateway as an example of this pattern implementation in Azure Service- it will be useful https://docs.microsoft.com/en-us/azure/application-gateway/overview#secure-sockets-layer-ssl-termination

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d673fcd-cabe-8ad9-c910-f1c1dd55ba07
* Version Independent ID: ed0eb171-640e-2269-aeb4-f936ccb34c7c
* Content: [Gateway Offloading pattern](https://docs.microsoft.com/en-us/azure/architecture/patterns/gateway-offloading)
* Content Source: [docs/patterns/gateway-offloading.md](https://github.com/mspnp/architecture-center/blob/master/docs/patterns/gateway-offloading.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hello @SychevIgor 

Thank you for valuable feedback! We will review and make any necessary changes.
