### ISSUE TITLE
Standard SSD Support

### ISSUE THREAD

**Issue by matheus-santoro** [mspnp/architecture-center#916]
Hello there

Any info about SAP Instances supporting the Standard SSD disks?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 009774ee-d1e4-1d7b-e53f-ecbcc4d56e5d
* Version Independent ID: d14a99bb-b4d5-21ce-dd72-5759a8284c42
* Content: [SAP S/4HANA for Linux Virtual Machines on Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/sap/sap-s4hana#recommendations)
* Content Source: [docs/reference-architectures/sap/sap-s4hana.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/sap/sap-s4hana.md)
* Service: **guidance**
* GitHub Login: @lbrader
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Per [this announcement](https://azure.microsoft.com/en-us/blog/announcing-general-availability-of-standard-ssd-disks-for-azure-virtual-machine-workloads/), Standard SSD is intended for low IOPS workloads, Premium SSD is recommended for enterprise workloads including SAP
