### ISSUE TITLE
Incorrect code block formatting

### ISSUE THREAD

**Issue by MWL88** [mspnp/architecture-center#919]
The code blocks following the 'Update the user secrets' heading are not formatted correctly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5df2491-1abe-0211-efbf-c1fb384862e9
* Version Independent ID: f7f0d2cf-3f4f-44dc-54aa-cd59221264d2
* Content: [Use Key Vault to protect application secrets](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/key-vault#feedback)
* Content Source: [docs/multitenant-identity/key-vault.md](https://github.com/mspnp/architecture-center/blob/master/docs/multitenant-identity/key-vault.md)
* Service: **guidance**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Ah, I see it now. Thanks! 😺
