### ISSUE TITLE
Missing access rights model for resource groups

### ISSUE THREAD

**Issue by MartinNr5** [mspnp/architecture-center#923]
Hi.

I'm of the opinion that you're missing the most useful access permission model for resource groups, namely giving the workload owners the Owner access level on their respective resource groups.

This way they only have access to their respective workloads and the subscription admin isn't overburdened with requests for adding users.

There is most likely no way for the subscription admin to know if the wrong people are asked to be added to the resource group to begin with so that really isn't a reason to prevent the workload owners from doing this themselves. 

There should also be multiple access review processes in place to make sure that only the correct accounts have the correct type of access. Azure Policy is one way to do this and there should also be existing access review processes in place, for on-premise resources, that should be re-useable for cloud resources.

If nothing else, I would very much like your analysis of this model to highlight the pros and cons.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 707f371c-3a15-6549-9092-113c0e9acf61
* Version Independent ID: 0b9646c0-b8e5-a402-f1be-2aad76d8ee89
* Content: [Enterprise Cloud Adoption: Governance design in Azure for multiple teams](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/governance/governance-multiple-teams?toc=/azure/governance/toc.json)
* Content Source: [docs/cloud-adoption/governance/governance-multiple-teams.md](https://github.com/mspnp/architecture-center/blob/master/docs/cloud-adoption/governance/governance-multiple-teams.md)
* Service: **guidance**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hello @MartinNr5 

Thank you for your feedback! We have assigned this issue to the author to review further and take the right course of action.

**Comment by Petertaylor9999** [comment]
Thanks @mike-urnun-msft - this content is currently undergoing a major revision. @BrianBlanchard is PM'ing this work and will be publishing in the near future.

**Comment by BrianBlanchard** [comment]
Great suggestion @MartinNr5 
 
As @Petertaylor9999 mentioned, we have a major revision of the content coming in early February. In the updated content, we are currently adhering to the guidance provided by the Azure AD team of taking a least privilege access model to ensure users are only able to complete necessary tasks. 

Another approach to consider could be the integration of Azure AD PIM to [create an approval workflow](https://docs.microsoft.com/en-us/azure/active-directory/privileged-identity-management/pim-resource-roles-configure-role-settings). That would limit access but still share administrative overhead with application owners.
