### ISSUE TITLE
Amazon Lightsail Description

### ISSUE THREAD

**Issue by PatMyron** [mspnp/architecture-center#928]
The description here for Amazon Lightsail:
"Collection of virtual machine templates to select from when building out your virtual machine."

does not line up with AWS' own description of the service: 
"Everything you need to jumpstart your project on AWS — compute, storage,
and networking — for a low, predictable price."
https://aws.amazon.com/lightsail/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [Azure and AWS services compared - multicloud](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/mspnp/architecture-center/blob/master/docs/aws-professional/services.md)
* Service: **guidance**
* GitHub Login: @lbrader
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Thanks for the feedback. The description column is actually describing the Azure service that is being compared. I think the point is that Lightsail deploys a pre-configured VM + apps. For Azure, the Azure Marketplace might be a better comparison.

**Comment by PatMyron** [comment]
@MikeWasson I'm not sure if that comparison is perfect either. Amazon LightSail is not a 3rd party marketplace. LightSail seems more comparable to something like Heroku or AWS Elastic Beanstalk than it does to Azure Marketplace
