### ISSUE TITLE
Why are you excluding App Service from hosting microservices?

### ISSUE THREAD

**Issue by sandeepmaurya** [mspnp/architecture-center#934]
App Service + ASP.NET Core provides a very mature framework for creating and hosting microservices when compared to basic functions with http triggers.
Regular API development would expect for example, DI support, role/claims based AuthZ, middlewares for token parsing/global exception handling/CSP header setting etc., data annotations. All these are built-in ASP.NET Core and App Service provides a natural hosting environment. With functions these need to implemented with extra work, still they are preferred over App Service. Can you explain please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Decision tree for Azure compute services](https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree#flowchart)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/mspnp/architecture-center/blob/master/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **guidance**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hello @sandeepmaurya

Thank you for your valuable feedback, and apologies for the delay in response. While App Service is definitely a mature product, Azure Functions provides higher layer of abstraction as PaaS and runs on top of App Service as well. As such, Functions carries all of the mature features that are in App Service with more ease of use for modern patterns and use-cases.
