### ISSUE TITLE
Add a note that HttpClient's DefaultRequestHeaders property is not thread-safe

### ISSUE THREAD

**Issue by kp101090** [mspnp/architecture-center#935]
DefaultRequestHeaders property of HttpClient is not thread-safe. If one uses DefaultRequestHeaders (which virtually all do) with shared instance of HttpClient, they can run into hard-to-detect race conditions. 
If following apparantly non problematic line is part of an async post\get, one will get key has already been added exception with two concurrent requests.

public async Task GetAsync(string blah)
{
client.DefaultRequestHeaders.Authorization = GetBearerTokenAsync();
// blah blah blah
}
Of course, there are ways to mitigate this, but if the official documentation page mentions such caveats, devs won't have to bang their head for countless hours before finding the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dfc831d-af15-b8a9-5fc6-335bce4af155
* Version Independent ID: e2370017-a358-c817-2a69-0d036066f5bf
* Content: [Improper Instantiation antipattern](https://docs.microsoft.com/en-us/azure/architecture/antipatterns/improper-instantiation/)
* Content Source: [docs/antipatterns/improper-instantiation/index.md](https://github.com/mspnp/architecture-center/blob/master/docs/antipatterns/improper-instantiation/index.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hello @kp101090 

Thank you for reporting this issue! We will investigate and make any necessary changes.

**Comment by MikeWasson** [comment]
Thanks - As this article is about the general pattern, I tried to generalize the advice, using `DefaultRequestHeaders ` as an example. I also opened an issue to address this in the API doc.
