### ISSUE TITLE
Maven Cache in Azure DevOps

### ISSUE THREAD

**Issue by mjbros** [mspnp/architecture-center#939]
When I build an open source application like Spring Pet Clinic in Azure DevOps, is there any way to cache maven dependencies with Azure, rather than downloading dependencies from maven central every time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8865190-b9ac-ae5e-2590-30237ed43697
* Version Independent ID: 45d8bb8c-10f1-de72-6644-a20ba60a32af
* Content: [CI/CD pipeline with Azure DevOps](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/devops-dotnet-webapp#deploy-the-scenario)
* Content Source: [docs/example-scenario/apps/devops-dotnet-webapp.md](https://github.com/mspnp/architecture-center/blob/master/docs/example-scenario/apps/devops-dotnet-webapp.md)
* Service: **guidance**
* GitHub Login: @christianreddington
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Hi - This is a feature request that's being tracked here:

https://visualstudio.uservoice.com/forums/330519-azure-devops-formerly-visual-studio-team-services/suggestions/32044321-improve-hosted-build-agent-performance-with-build

**Comment by milespop** [comment]
Bump
