### ISSUE TITLE
Error in docs: Azure Analysis Services does not support multidimensional (MOLAP)

### ISSUE THREAD

**Issue by wlodekbielski** [mspnp/architecture-center#960]
"Azure Analysis Services supports the creation of multidimensional and tabular models to meet this need." - this is not fully true, as AAS currently does not support multidimensional models. Only tabular models are supported, and lack of multidimensional is major issue for lots of enterprise customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7552eb5d-ab91-185b-d6af-fa6aaa233e00
* Version Independent ID: 78d69947-f8c1-9978-476a-58b0763d9eb5
* Content: [Batch processing](https://docs.microsoft.com/en-us/azure/architecture/data-guide/big-data/batch-processing)
* Content Source: [docs/data-guide/big-data/batch-processing.md](https://github.com/mspnp/architecture-center/blob/master/docs/data-guide/big-data/batch-processing.md)
* Service: **guidance**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Yes - that's definitely an error in the doc, thanks
