### ISSUE TITLE
Why can't we rewrite this pattern like this?

### ISSUE THREAD

**Issue by Aravin** [mspnp/architecture-center#961]
```
for (int i=0; i < retryCount; i++)
  {
    try
    {
      // Call external service.
      // Consider this is know method, either return `success` or `failure`
      var status = await TransientOperationAsync();
      
      if (status == 'success')
           return true;

       throw;
    }
    catch (Exception ex)
    {
      currentRetry++;

      if (currentRetry > this.retryCount || !IsTransient(ex))
      {
        // If this isn't a transient error or we shouldn't retry, 
        // rethrow the exception.
        throw;
      }
    }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 497c1436-d32c-1fb5-3209-22058fece4b2
* Version Independent ID: 4818d7be-c866-39bc-f2c3-d7af59d2cd4e
* Content: [Retry](https://docs.microsoft.com/en-us/azure/architecture/patterns/retry)
* Content Source: [docs/patterns/retry.md](https://github.com/mspnp/architecture-center/blob/master/docs/patterns/retry.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
The first throw isn't inside a catch block. Also you have a possible case where i == retryCount, and you don't re-throw the exception but you exit the loop, swallowing the exception.

**Comment by Aravin** [comment]
My idea is to replace infinite loop `(;;)` with  finite loop`(int i=0; i < retryCount; i++)`

@MikeWasson , Thanks for the Answer, however I got same output for both the method.
