### ISSUE TITLE
Wrong Visio Linked For AD FS Extension To Azure

### ISSUE THREAD

**Issue by sbalogunpcgus** [mspnp/architecture-center#975]
Hello,

When i download the Visio above by clicking the "Download a Visio file of this architecture." link, what downloads is one for AD DS (Active Directory Domain Services)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e67f48d5-1891-05be-e74f-d4003e9f8bea
* Version Independent ID: 5ac877a7-dce1-ca0a-4487-d0336a351581
* Content: [Implementing Active Directory Federation Services (AD FS) in Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adfs)
* Content Source: [docs/reference-architectures/identity/adfs.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/identity/adfs.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Hi - The Visio download contains all of the on-premise identity reference architectures. The AD FS one is the fourth tab.

**Comment by sbalogunpcgus** [comment]
Thank you @MikeWasson , entirely missed that. My apologies.
