### ISSUE TITLE
spelling and grammar mistakes

### ISSUE THREAD

**Issue by shawarbiny** [mspnp/architecture-center#980]
Spelling mistake in "minimumal " in Azure Site Recovery section.

Grammar mistake in "to handling" in the introduction

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cefa78da-afbb-5529-d707-b158d991cb16
* Version Independent ID: 64342775-2746-0e51-9aba-253074530f27
* Content: [Disaster recovery for Azure applications](https://docs.microsoft.com/en-us/azure/architecture/resiliency/disaster-recovery-azure-applications)
* Content Source: [docs/resiliency/disaster-recovery-azure-applications.md](https://github.com/mspnp/architecture-center/blob/master/docs/resiliency/disaster-recovery-azure-applications.md)
* Service: **guidance**
* GitHub Login: @adamglick
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hello @shawarbiny Thank you for reporting this issue! We will review and make any necessary changes.
