### ISSUE TITLE
Add databricks

### ISSUE THREAD

**Issue by patpicos** [mspnp/architecture-center#981]
There are no mentions of azure databricks in the comparison. Line it up with amazon emr

**Comment by mike-urnun-msft** [comment]
Hello @patpicos 

Thank you for your feedback. Since this is a duplicate of #984, we will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Comment by patpicos** [comment]
thanks. i was having issues b/w the comment page and github..
