### ISSUE TITLE
Multi-request and shared HttpClient

### ISSUE THREAD

**Issue by PingPongSet** [mspnp/architecture-center#986]
If we re-use HttpClient like in SingleHttpClientInstanceController , what if multi requests come in, and the current request is using the shared HttpClient, will this case block subsequent requests? 

I have a Web API that accepts request, and calls external web services, if calling external web API blocks, will it block all in coming requests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dfc831d-af15-b8a9-5fc6-335bce4af155
* Version Independent ID: e2370017-a358-c817-2a69-0d036066f5bf
* Content: [Improper Instantiation antipattern](https://docs.microsoft.com/en-us/azure/architecture/antipatterns/improper-instantiation/)
* Content Source: [docs/antipatterns/improper-instantiation/index.md](https://github.com/mspnp/architecture-center/blob/master/docs/antipatterns/improper-instantiation/index.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
If you use the async methods then you aren't blocking any threads while waiting for the response.

**Comment by PingPongSet** [comment]
Even using async, it is possible that new request comes in if there is only one HttpClient instance is working. pls correct me if I am wrong. unless it is managed by a factory like in ASP.NET core HttpClientFactory. But I am not sure.

**Comment by MikeWasson** [comment]
See [this doc](https://docs.microsoft.com/dotnet/csharp/programming-guide/concepts/async/how-to-make-multiple-web-requests-in-parallel-by-using-async-and-await)

Your Web API controller method should be async as well.
