### ISSUE TITLE
Tool Used

### ISSUE THREAD

**Issue by sreenathmadyastha** [mspnp/architecture-center#991]
Can anyone guide me what tool used to create architecture diagram like above ? if that is Visio where can I get those stencils?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5c2b717-8cbb-8794-3a5c-3086e76f1717
* Version Independent ID: 6d6ea7d8-05ec-7903-1df5-6d3fc248a123
* Content: [IoT and data analytics in the construction industry](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/data/big-data-with-iot)
* Content Source: [docs/example-scenario/data/big-data-with-iot.md](https://github.com/mspnp/architecture-center/blob/master/docs/example-scenario/data/big-data-with-iot.md)
* Service: **guidance**
* GitHub Login: @alexbuckgit
* Microsoft Alias: **pnp**

**Comment by alexbuckgit** [comment]
I think that the icons used in these diagrams are the ones available here:
https://www.microsoft.com/en-us/download/details.aspx?id=41937

**Comment by mike-urnun-msft** [comment]
Hello @sreenathmadyastha 

We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
